class_name CyborgSuit
extends RefCounted
## The cyborgs' look on the shared HumanoidRig (GDD §9.2 production note: "one shared body and
## skeleton with swappable parts per zone"), generated by code (CLAUDE.md, Assets). One HumanoidParts:
## the cyborg skeleton, the few pieces every look shares, and one attachment set per look, switched on
## with HumanoidRig.set_attachments().
##
## The base look (GDD §9.2, "Base look"; brief docs/art/BRIEF_CYBORG_GANGSTER.md; the owner's concept
## sheet docs/art/reference/cyborg_viewing_devices.jpg, Variant 1, the "Static TV Head" Infiltrator):
## a ragged, strung-out gangster. The whole head is a beat-up CRT television (a boxy casing with a
## dented bezel, vents and a tapered back) whose screen is the face; a worn leather vest open over an
## olive hoodie with a torn hem and the hood bunched round a ribbed neck; patched cargo pants and laced,
## scuffed boots; a boxy backpack with thick cables running up into the screen head and a hose over
## the right shoulder; and a scavenged cyber arm on the right that ends in the arm cannon (the arm the
## cyborgs fire from). The left arm is a thin one in the hoodie's sleeve, with a bare, bony hand.
## Posture (gaunt, hunched, twitchy) is CyborgPoses'.
##
## Colour rules (GDD §9.2): the clothing is grimy khaki, olive, brown and faded grey; the metal rusted
## steel and gunmetal, dull and unlit (the sheet's brass arm is rusted steel here). Nothing on it
## glows but the screen's cold white face, the cannon's red charge-up (the emitter ring and orb,
## unchanged), and on hosts only the purple glitching screen and purple veins along the neck and arms
## (the &"host" set). Nothing glows copper (Razor Echo's signature, GDD §11); no hazard or "safe"
## colour anywhere else. test_cyborg_body.gd pins these rules.
##
## Looks: a skin's `enemy_variant` picks one (look_for). The base is the only one so far and every
## zone wears it; the zone variants (GDD §9.2, task P3) are tweaks of it, added as attachment sets
## (built from the base's part builders below) with their own entry in LOOKS. Every look shares the
## skeleton, the hitboxes, the faces, the colour rules and the cannon's charge-up.
##
## Hands and feet ride on the forearms and shins, and the neck, backpack and cables on the chest, so a
## whole cyborg is 11 segment meshes (11 draw calls) and a window cyborg's upper body 7. The screen,
## ring, orb and veins are marked pieces in the same meshes that cyborg_body.gdshader draws with the
## body. The cables and the shoulder hose belong to the chest and end inside the TV and the shoulder
## cap, near their pivots, so they stay plugged in however the head and arm turn. One material per
## cyborg.
##
## Rig convention (HumanoidPiece): metres, +y up, -z forward (where the cyborg faces), +x its right.
## Limb pieces are authored for the right limb; RIGHT-only pieces are the cyber arm's, LEFT-only ones
## the hoodie sleeve's and the left leg's.

const Kit = preload("res://scripts/enemies/cyborg_kit.gd")
const SHADER: Shader = preload("res://scripts/enemies/cyborg_body.gdshader")
const CACHE_KEY: String = "cyborg_v2"
## Every look, by name (the attachment set that dresses it). Zone variants (task P3) add theirs.
const LOOKS: Array[StringName] = [&"base"]
const BASE: StringName = &"base"
## The hosts' veins (GDD §9.7), worn on top of the look.
const HOST_SET: StringName = &"host"
const WALK_TUNING_PATH: String = "res://data/tuning/cyborg_walk_animation.tres"
const RUN_TUNING_PATH: String = "res://data/tuning/cyborg_run_animation.tres"

## Glow values marking the pieces cyborg_body.gdshader draws specially.
const SCREEN: float = 10.0
const RING: float = 20.0
const ORB: float = 30.0
const VEIN: float = 40.0

## The screen head (head segment space): the TV's front section (the bezel box) and the screen, the
## face, recessed in its bezel. The shader maps the face onto the screen's rectangle.
const TV_SIZE := Vector3(0.4, 0.31, 0.12)
const TV_CENTER := Vector3(0.0, 0.145, -0.08)
const SCREEN_CENTER := Vector3(0.0, 0.155, -0.142)
const SCREEN_SIZE := Vector3(0.33, 0.23, 0.01)
## The charge orb on the cannon forearm (segment space): the cannon's tip.
const MUZZLE := Vector3(0.0, -0.43, 0.0)

## The torso: the hoodie's section (a 12-sided ring, half sizes) swept through these rings (height in
## the chest joint's space, x scale, z scale, z shift): from its torn hem at the hips, a thin waist,
## narrow chest and bony shoulders rolled a little forward, up round the neck. The vest is the same
## shape VEST_GAP larger, open at the front.
const TORSO_HALF := Vector2(0.12, 0.082)
const TORSO_RINGS: Array[Vector4] = [
	Vector4(-0.1, 0.98, 1.0, 0.0),
	Vector4(0.0, 0.97, 1.0, 0.0),
	Vector4(0.14, 1.05, 1.05, 0.0),
	Vector4(0.29, 1.15, 1.06, -0.006),
	Vector4(0.365, 1.52, 0.97, -0.01),
	Vector4(0.415, 0.95, 0.74, -0.004),
]
const VEST_GAP: float = 0.016
## The vest's hem (chest joint space): above the hoodie's, so the torn hoodie shows below it.
const VEST_HEM: float = -0.035

## Clothing (grimy khaki, olive, brown and faded grey; nothing on it glows).
const HOODIE := Color(0.37, 0.37, 0.27)
const HOODIE_SHADE := Color(0.28, 0.28, 0.21)
const HOODIE_FRAYED := Color(0.47, 0.45, 0.35)
const VEST := Color(0.21, 0.16, 0.13)
const VEST_WORN := Color(0.31, 0.25, 0.2)
const PANTS := Color(0.31, 0.32, 0.25)
const PANTS_SHADE := Color(0.24, 0.25, 0.2)
const PATCH := Color(0.43, 0.4, 0.32)
const PATCH_GREY := Color(0.38, 0.38, 0.36)
const BOOT := Color(0.27, 0.2, 0.15)
const BOOT_SCUFF := Color(0.37, 0.32, 0.27)
const SOLE := Color(0.1, 0.095, 0.1)
const LACE := Color(0.15, 0.14, 0.12)
const STRAP := Color(0.15, 0.14, 0.13)
## A pale, sallow hand (it isn't clothing, but it keeps to the same dull range).
const SKIN := Color(0.6, 0.54, 0.49)
const SKIN_SHADE := Color(0.5, 0.45, 0.41)
## Metal (dull and unlit): rusted steel, gunmetal, and the TV's grimy casing.
const STEEL := Color(0.44, 0.44, 0.43)
const RUST := Color(0.37, 0.25, 0.18)
const GUNMETAL := Color(0.2, 0.21, 0.22)
const CASING := Color(0.52, 0.51, 0.47)
const CASING_DARK := Color(0.32, 0.32, 0.31)
const GRIME := Color(0.26, 0.25, 0.23)
const PACK := Color(0.3, 0.32, 0.28)
const RUBBER := Color(0.09, 0.09, 0.09)
const RUBBER_RIB := Color(0.15, 0.15, 0.15)
const CABLE := Color(0.14, 0.14, 0.14)
const HOSE := Color(0.3, 0.25, 0.21)
## Dull metal catches a little light (HumanoidPiece.shine): never polished, never glowing.
const METAL_SHINE: float = 0.25

const BOX := HumanoidPiece.Shape.BOX
const PRISM := HumanoidPiece.Shape.PRISM
const LATHE := HumanoidPiece.Shape.LATHE
const BAND := HumanoidPiece.Shape.BAND
const SHELL := HumanoidPiece.Shape.SHELL
const MIRRORED := HumanoidPiece.Placement.MIRRORED
const RIGHT := HumanoidPiece.Placement.RIGHT
const LEFT := HumanoidPiece.Placement.LEFT

static var _parts: HumanoidParts
static var _walk: HumanoidAnimTuning
static var _run: HumanoidAnimTuning


static func parts() -> HumanoidParts:
	if _parts == null:
		_parts = _build_parts()
	return _parts


## The look a skin's enemy_variant dresses the cyborgs in: its own when it has one, else the base.
## (The skins' current variants, &"city" and &"scavenger", still pick the other enemies' weathering.)
static func look_for(variant: StringName) -> StringName:
	return variant if LOOKS.has(variant) else BASE


## The attachment sets a cyborg wears: its look, plus the veins on a host.
static func attachment_sets(look: StringName, host: bool) -> Array[StringName]:
	var sets: Array[StringName] = [look_for(look)]
	if host:
		sets.append(HOST_SET)
	return sets


## A new material for one cyborg (its face, charge, flash and death are its own).
static func new_material(look: StringName, host: bool, visual_seed: int) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = SHADER
	m.set_shader_parameter(&"led_color", Kit.LED_COLOR)
	m.set_shader_parameter(&"glitch_color", Kit.GLITCH_COLOR)
	m.set_shader_parameter(&"glitch", 1.0 if host else 0.0)
	m.set_shader_parameter(&"seed", float(visual_seed % 997))
	m.set_shader_parameter(&"charge_color", Kit.CHARGE_COLOR)
	m.set_shader_parameter(&"orb_center", MUZZLE)
	m.set_shader_parameter(&"screen_rect", screen_rect(look))
	m.set_shader_parameter(&"face_grid", Vector2(Kit.FACE_GRID))
	m.set_shader_parameter(&"face", Kit.face_texture(Kit.Face.NEUTRAL))
	return m


## The screen's rectangle in the head segment's space (x min, y min, x max, y max) for a look.
static func screen_rect(_look: StringName) -> Vector4:
	var half := Vector2(SCREEN_SIZE.x, SCREEN_SIZE.y) * 0.5
	return Vector4(SCREEN_CENTER.x - half.x, SCREEN_CENTER.y - half.y, SCREEN_CENTER.x + half.x,
		SCREEN_CENTER.y + half.y)


## The walk cycle's pose numbers (data/tuning/cyborg_walk_animation.tres; also the idle breathing).
static func walk_tuning() -> HumanoidAnimTuning:
	if _walk == null:
		_walk = _load_tuning(WALK_TUNING_PATH)
	return _walk


## The panic variant's sprint (data/tuning/cyborg_run_animation.tres).
static func run_tuning() -> HumanoidAnimTuning:
	if _run == null:
		_run = _load_tuning(RUN_TUNING_PATH)
	return _run


static func _load_tuning(path: String) -> HumanoidAnimTuning:
	var t: HumanoidAnimTuning = load(path) as HumanoidAnimTuning if ResourceLoader.exists(path) else null
	return t if t != null else HumanoidAnimTuning.new()


static func _build_parts() -> HumanoidParts:
	var p := HumanoidParts.new()
	p.cache_key = CACHE_KEY
	# The cyborg as modelled, standing: the TV's top is 1.54 m up.
	p.design_size = Vector3(0.62, 1.54, 0.46)
	# The cyborg skeleton (unchanged, so every pose keeps its reach): hips at 0.7 m, shoulders at
	# 1.16 m, the head joint at 1.24 m.
	p.hip_offset = Vector3(0.085, -0.05, 0.0)
	p.thigh_length = 0.33
	p.shin_length = 0.26
	p.ankle_height = 0.06
	p.chest_offset = Vector3(0.0, 0.06, 0.0)
	p.neck_offset = Vector3(0.0, 0.45, 0.0)
	p.head_offset = Vector3(0.0, 0.03, 0.0)
	p.shoulder_offset = Vector3(0.23, 0.4, 0.0)
	p.upper_arm_length = 0.28
	p.forearm_length = 0.25
	p.pieces = _shared()
	p.attachments = {BASE: _base_look(), HOST_SET: _host_veins()}
	return p


## Shared by every look: the boot soles and the cannon's emitter ring and charge orb (the charge-up
## looks the same in every zone, GDD §9.2). The soles must be here: HumanoidRig puts a body on the
## ground by the lowest points of its bare segments (no attachment sets).
static func _shared() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_add(list, &"shin", BOX, Vector3(0.105, 0.06, 0.205), Vector3(0.0, -0.31, -0.03), SOLE, 0.0,
		{"top_scale": Vector2(0.9, 0.85)})
	_add(list, &"forearm", PRISM, Vector3(0.136, 0.03, 0.136), Vector3(0.0, -0.405, 0.0), Color.WHITE, RING,
		{"side": RIGHT, "sides": 8})
	var rings := PackedVector4Array()
	for k: int in 7:
		var a: float = PI * k / 6.0
		rings.append(Vector4(-cos(a) * 0.075, sin(a), sin(a), 0.0))
	_add(list, &"forearm", LATHE, Vector3(0.15, 0.0, 0.15), MUZZLE, Color.WHITE, ORB,
		{"side": RIGHT, "sides": 8, "profile": rings})
	return list


## The base look, Variant 1: the "Static TV Head" Infiltrator.
static func _base_look() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_screen_head(list)
	_hoodie(list)
	_vest(list)
	_backpack(list)
	_free_arm(list)
	_cyber_arm(list)
	_legs(list)
	return list


## The whole head is a beat-up CRT television (no hair, face or mask): a grimy casing with a dented
## bezel round the screen, a vented chin with two knobs, vents in the sides, the tapered back of the
## tube and a vented back plate. The screen is the face (glow SCREEN).
static func _screen_head(list: Array[HumanoidPiece]) -> void:
	var front: float = TV_CENTER.z - TV_SIZE.z * 0.5
	var top: float = TV_CENTER.y + TV_SIZE.y * 0.5
	_add(list, &"head", BOX, TV_SIZE, TV_CENTER, CASING, 0.0, {"chamfer": 0.12})
	# The tube's tapered back: +y of the box points back (+z), and its far end is smaller.
	_add(list, &"head", BOX, Vector3(0.34, 0.15, 0.25), Vector3(0.0, 0.14, 0.055), CASING_DARK, 0.0,
		{"rotation_degrees": Vector3(90.0, 0.0, 0.0), "top_scale": Vector2(0.72, 0.7), "chamfer": 0.1})
	_add(list, &"head", BOX, Vector3(0.21, 0.15, 0.022), Vector3(0.0, 0.14, 0.135), GUNMETAL)
	for k: int in 3:
		_add(list, &"head", BOX, Vector3(0.15, 0.012, 0.006), Vector3(0.0, 0.18 - k * 0.034, 0.148), RUBBER)
	# The bezel, proud of the casing round the recessed screen: a thick chin, the top bar knocked a
	# little askew and the left side pushed in (dents). (The shader draws the dark lip round the glass.)
	var bezel_z: float = front - 0.007
	var s := SCREEN_SIZE
	var c := SCREEN_CENTER
	_add(list, &"head", BOX, Vector3(TV_SIZE.x, 0.03, 0.02), Vector3(0.0, c.y + s.y * 0.5 + 0.015, bezel_z), CASING,
		0.0, {"rotation_degrees": Vector3(0.0, 0.0, 1.2)})
	_add(list, &"head", BOX, Vector3(TV_SIZE.x, 0.052, 0.02), Vector3(0.0, c.y - s.y * 0.5 - 0.026, bezel_z), CASING)
	_add(list, &"head", BOX, Vector3(0.035, s.y + 0.01, 0.02), Vector3(c.x + s.x * 0.5 + 0.0175, c.y, bezel_z), CASING)
	_add(list, &"head", BOX, Vector3(0.035, s.y + 0.01, 0.016), Vector3(c.x - s.x * 0.5 - 0.0175, c.y, bezel_z + 0.004),
		CASING, 0.0, {"rotation_degrees": Vector3(0.0, 3.0, 0.0)})
	# The screen, recessed in the bezel.
	_add(list, &"head", BOX, SCREEN_SIZE, SCREEN_CENTER, Color.BLACK, SCREEN)
	# The chin's vent slits and two knobs.
	var chin_y: float = c.y - s.y * 0.5 - 0.026
	for k: int in 3:
		_add(list, &"head", BOX, Vector3(0.03, 0.008, 0.004), Vector3(-0.14 + k * 0.042, chin_y, bezel_z - 0.011), RUBBER)
	for x: float in [0.12, 0.152]:
		_add(list, &"head", PRISM, Vector3(0.02, 0.012, 0.02), Vector3(x, chin_y, bezel_z - 0.014), GUNMETAL, 0.0,
			{"sides": 6, "rotation_degrees": Vector3(90.0, 0.0, 0.0)})
	# Vents in both sides; grime, rust streaks and a dent on the casing.
	for k: int in 3:
		_add(list, &"head", BOX, Vector3(0.005, 0.01, 0.075), Vector3(TV_SIZE.x * 0.5 + 0.002, 0.22 - k * 0.026, -0.075),
			RUBBER, 0.0, {"side": MIRRORED})
	_add(list, &"head", BOX, Vector3(0.14, 0.004, 0.08), Vector3(-0.05, top + 0.001, -0.075), GRIME, 0.0,
		{"rotation_degrees": Vector3(0.0, 12.0, 0.0)})
	_add(list, &"head", BOX, Vector3(0.06, 0.004, 0.05), Vector3(0.12, top + 0.001, -0.1), RUST)
	_add(list, &"head", BOX, Vector3(0.05, 0.03, 0.03), Vector3(-0.13, top - 0.008, -0.05), GRIME, 0.0,
		{"rotation_degrees": Vector3(0.0, 0.0, 18.0)})
	_add(list, &"head", BOX, Vector3(0.004, 0.08, 0.05), Vector3(TV_SIZE.x * 0.5 + 0.002, 0.07, -0.11), RUST)
	_add(list, &"head", BOX, Vector3(0.022, 0.07, 0.004), Vector3(0.165, 0.255, bezel_z - 0.0105), RUST, 0.0,
		{"rotation_degrees": Vector3(0.0, 0.0, -6.0)})
	_add(list, &"head", BOX, Vector3(0.06, 0.035, 0.004), Vector3(-0.15, 0.012, bezel_z - 0.0105), GRIME)


## The hoodie: the torso (hem to shoulders, round the neck), a torn and frayed hem hanging below the
## vest, the hood bunched round a ribbed neck, and the drawstrings.
static func _hoodie(list: Array[HumanoidPiece]) -> void:
	_add(list, &"chest", LATHE, Vector3(TORSO_HALF.x * 2.0, 0.0, TORSO_HALF.y * 2.0), Vector3.ZERO, HOODIE, 0.0,
		{"sides": 12, "profile": PackedVector4Array(TORSO_RINGS)})
	# A frayed band along the hem, and torn strips hanging from it (the sheet's ragged layers).
	var hem: Vector4 = TORSO_RINGS[0]
	var r := Vector2(TORSO_HALF.x * hem.y, TORSO_HALF.y * hem.z)
	_add(list, &"chest", BAND, Vector3(r.x * 2.0 + 0.006, 0.0, r.y * 2.0 + 0.006), Vector3.ZERO, HOODIE_FRAYED, 0.0,
		{"sides": 12, "profile": PackedVector4Array([Vector4(hem.x, 1.0, 1.0, 0.0), Vector4(hem.x + 0.025, 1.0, 1.0, 0.0)])})
	for tooth: Vector3 in [Vector3(-100.0, 0.05, 0.05), Vector3(-55.0, 0.05, 0.045), Vector3(-12.0, 0.055, 0.06),
			Vector3(30.0, 0.045, 0.04), Vector3(95.0, 0.05, 0.05), Vector3(150.0, 0.05, 0.055),
			Vector3(-150.0, 0.05, 0.045)]:
		# A wedge (its top face pinched to an edge), flipped so the point hangs down, turned to the waist.
		var a: float = deg_to_rad(tooth.x)
		var at := Vector3(sin(a) * (r.x + 0.002), hem.x - tooth.z * 0.5 + 0.004, -cos(a) * (r.y + 0.002))
		_add(list, &"chest", BOX, Vector3(tooth.y, tooth.z, 0.012), at, HOODIE_FRAYED, 0.0,
			{"top_scale": Vector2(0.0, 1.0), "rotation_degrees": Vector3(180.0, -tooth.x, 0.0)})
	# The ribbed neck (the sheet's black corrugated neck) and the hood bunched round its base.
	_add(list, &"chest", PRISM, Vector3(0.066, 0.11, 0.066), Vector3(0.0, 0.455, 0.0), RUBBER, 0.0, {"sides": 6})
	for y: float in [0.44, 0.47]:
		_add(list, &"chest", PRISM, Vector3(0.08, 0.016, 0.08), Vector3(0.0, y, 0.0), RUBBER_RIB, 0.0, {"sides": 6})
	_add(list, &"chest", LATHE, Vector3(0.17, 0.0, 0.15), Vector3(0.0, 0.0, 0.012), HOODIE_SHADE, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(0.385, 0.95, 0.95, 0.0), Vector4(0.418, 1.08, 1.12, 0.008),
			Vector4(0.445, 0.7, 0.72, 0.012)])})
	_add(list, &"chest", BOX, Vector3(0.16, 0.09, 0.05), Vector3(0.0, 0.378, 0.092), HOODIE_SHADE, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(0.85, 0.75), "rotation_degrees": Vector3(-28.0, 0.0, 0.0)})
	for x: float in [-0.026, 0.026]:
		_pipe(list, &"chest", Vector3(x, 0.395, -0.068), Vector3(x * 1.1, 0.285, -0.099), 0.009, HOODIE_FRAYED, 4)


## The worn leather vest, open over the hoodie: the torso's shape a little larger, the front left
## open (a band: its inside only ever faces the hoodie), turned-back lapels, flap pockets and scuffs.
static func _vest(list: Array[HumanoidPiece]) -> void:
	var rings := PackedVector4Array()
	rings.append(Vector4(VEST_HEM, 0.975, 1.0, 0.0))
	for ring: Vector4 in TORSO_RINGS:
		if ring.x > VEST_HEM and ring.x < 0.2:
			continue  # One ring less: the vest hangs straighter than the hoodie.
		if ring.x > VEST_HEM:
			rings.append(ring)
	var half := TORSO_HALF + Vector2.ONE * VEST_GAP
	_add(list, &"chest", BAND, Vector3(half.x * 2.0, 0.0, half.y * 2.0), Vector3.ZERO, VEST, 0.0,
		{"sides": 12, "arc": Vector2(25.0, 335.0), "profile": rings})
	# The lapels, turned back at the top of the open front, lying on the facets beside the opening
	# (the ring's facets there run about 18° off the front).
	_add(list, &"chest", BOX, Vector3(0.05, 0.13, 0.012), Vector3(0.083, 0.325, -0.117), VEST_WORN, 0.0,
		{"side": MIRRORED, "top_scale": Vector2(1.4, 1.0), "rotation_degrees": Vector3(-8.0, -18.0, -14.0)})
	# Flap pockets on the front panels, and scuffs.
	_add(list, &"chest", BOX, Vector3(0.045, 0.05, 0.012), Vector3(0.088, 0.15, -0.099), VEST_WORN, 0.0,
		{"side": MIRRORED, "rotation_degrees": Vector3(0.0, -23.0, 0.0)})
	_add(list, &"chest", BOX, Vector3(0.07, 0.05, 0.006), Vector3(-0.07, 0.07, 0.106), VEST_WORN, 0.0,
		{"rotation_degrees": Vector3(0.0, 0.0, 20.0)})
	_add(list, &"chest", BOX, Vector3(0.012, 0.08, 0.05), Vector3(0.158, 0.18, 0.03), VEST_WORN)


## The boxy backpack: a metal unit with a lid, vents, a dial, a side cell and rust, strapped over the
## shoulders; two thick cables run from its top up into the screen head and a hose over the right
## shoulder into the cyber arm. They end inside the TV and the shoulder cap near their pivots, so they
## stay plugged in when the head or the arm turns.
static func _backpack(list: Array[HumanoidPiece]) -> void:
	_add(list, &"chest", BOX, Vector3(0.25, 0.28, 0.12), Vector3(0.0, 0.215, 0.165), PACK, 0.0,
		{"chamfer": 0.2, "shine": METAL_SHINE})
	_add(list, &"chest", BOX, Vector3(0.26, 0.035, 0.13), Vector3(0.0, 0.37, 0.165), GUNMETAL, 0.0,
		{"chamfer": 0.2, "shine": METAL_SHINE})
	_add(list, &"chest", BOX, Vector3(0.13, 0.03, 0.06), Vector3(0.0, 0.395, 0.19), GUNMETAL)
	for k: int in 3:
		_add(list, &"chest", BOX, Vector3(0.15, 0.014, 0.006), Vector3(-0.025, 0.285 - k * 0.034, 0.227), RUBBER)
	_add(list, &"chest", PRISM, Vector3(0.04, 0.02, 0.04), Vector3(0.078, 0.295, 0.233), STEEL, 0.0,
		{"sides": 8, "rotation_degrees": Vector3(90.0, 0.0, 0.0), "shine": METAL_SHINE})
	_add(list, &"chest", BOX, Vector3(0.05, 0.09, 0.004), Vector3(0.08, 0.17, 0.227), RUST)
	_add(list, &"chest", BOX, Vector3(0.045, 0.14, 0.09), Vector3(-0.145, 0.19, 0.17), GUNMETAL)
	# Webbing straps from the top of the pack over the shoulders to the chest.
	for side: float in [-1.0, 1.0]:
		var a := Vector3(side * 0.085, 0.355, 0.11)
		var b := Vector3(side * 0.12, 0.43, 0.012)
		var c := Vector3(side * 0.11, 0.3, -0.11)
		_bar(list, &"chest", a, b, Vector2(0.034, 0.01), STRAP, Vector3.UP)
		_bar(list, &"chest", b, c, Vector2(0.034, 0.01), STRAP, Vector3.FORWARD)
	# Cables looping up from the pack behind the neck into the back of the screen head (the head joint
	# is at y 0.48). They end inside the TV, within about 0.11 m of that joint, where the tube stays
	# round them however far the head turns.
	_cable(list, [Vector3(-0.045, 0.395, 0.205), Vector3(-0.06, 0.5, 0.25), Vector3(-0.055, 0.585, 0.21),
		Vector3(-0.04, 0.585, 0.1)], 0.036, CABLE)
	_cable(list, [Vector3(0.045, 0.395, 0.205), Vector3(0.07, 0.48, 0.235), Vector3(0.06, 0.55, 0.2),
		Vector3(0.045, 0.56, 0.09)], 0.028, CABLE)
	# The hose over the right shoulder (standing out past the TV's side from the front), into the
	# cyber arm's shoulder cap (the shoulder joint is at (0.23, 0.4, 0); it ends within 0.035 m of it).
	_cable(list, [Vector3(0.11, 0.3, 0.22), Vector3(0.24, 0.39, 0.2), Vector3(0.285, 0.48, 0.1),
		Vector3(0.232, 0.428, 0.022)], 0.042, HOSE)


## The left arm: thin, in the hoodie's sleeve, ending in a bare, bony hand.
static func _free_arm(list: Array[HumanoidPiece]) -> void:
	var sleeve := {"side": LEFT, "sides": 8}
	_add(list, &"upper_arm", PRISM, Vector3(0.106, 0.08, 0.1), Vector3(0.004, -0.02, 0.0), HOODIE, 0.0,
		_with(sleeve, {"top_scale": Vector2(0.7, 0.72)}))
	_add(list, &"upper_arm", PRISM, Vector3(0.084, 0.23, 0.084), Vector3(0.0, -0.145, 0.0), HOODIE, 0.0,
		_with(sleeve, {"top_scale": Vector2(1.14, 1.14)}))
	_add(list, &"upper_arm", PRISM, Vector3(0.082, 0.05, 0.082), Vector3(0.0, -0.272, 0.0), HOODIE_SHADE, 0.0, sleeve)
	_add(list, &"forearm", PRISM, Vector3(0.078, 0.19, 0.078), Vector3(0.0, -0.095, 0.0), HOODIE, 0.0,
		_with(sleeve, {"top_scale": Vector2(1.06, 1.06)}))
	_add(list, &"forearm", PRISM, Vector3(0.072, 0.04, 0.072), Vector3(0.0, -0.205, 0.0), HOODIE_SHADE, 0.0, sleeve)
	_add(list, &"forearm", PRISM, Vector3(0.036, 0.035, 0.04), Vector3(0.0, -0.235, 0.0), SKIN, 0.0,
		{"side": LEFT, "sides": 6})
	# The hand hangs palm in (thin across the palm, x), thumb forward, fingers a little curled.
	_add(list, &"forearm", BOX, Vector3(0.028, 0.065, 0.058), Vector3(0.0, -0.276, -0.004), SKIN, 0.0,
		{"side": LEFT, "chamfer": 0.3})
	_add(list, &"forearm", BOX, Vector3(0.024, 0.058, 0.05), Vector3(0.002, -0.334, -0.012), SKIN_SHADE, 0.0,
		{"side": LEFT, "top_scale": Vector2(1.0, 1.1), "rotation_degrees": Vector3(-14.0, 0.0, 0.0)})
	_add(list, &"forearm", BOX, Vector3(0.017, 0.046, 0.018), Vector3(-0.006, -0.282, -0.04), SKIN, 0.0,
		{"side": LEFT, "rotation_degrees": Vector3(-24.0, 0.0, 0.0)})


## The scavenged cyber arm on the right, in rusted steel and gunmetal (the sheet's brass arm, dulled):
## a domed shoulder cap, plates over a gunmetal core, a piston and the hose down its back, the elbow
## joint, and the forearm that is the arm cannon: a gunmetal breech, a steel barrel with cooling fins,
## a rusted patch plate, a feed cable and the muzzle collar, then the emitter ring and charge orb
## (shared pieces) at the tip.
static func _cyber_arm(list: Array[HumanoidPiece]) -> void:
	var metal := {"side": RIGHT, "shine": METAL_SHINE}
	_add(list, &"upper_arm", LATHE, Vector3(0.13, 0.0, 0.13), Vector3(0.008, 0.0, 0.0), STEEL, 0.0, _with(metal, {
		"sides": 8, "profile": PackedVector4Array([Vector4(-0.05, 0.9, 0.9, 0.0), Vector4(-0.01, 1.0, 1.0, 0.0),
			Vector4(0.035, 0.72, 0.72, 0.0), Vector4(0.056, 0.3, 0.3, 0.0)])}))
	_add(list, &"upper_arm", BAND, Vector3(0.121, 0.0, 0.121), Vector3(0.008, 0.0, 0.0), RUST, 0.0, {"side": RIGHT,
		"sides": 8, "profile": PackedVector4Array([Vector4(-0.05, 0.96, 0.96, 0.0), Vector4(-0.036, 0.98, 0.98, 0.0)])})
	_add(list, &"upper_arm", PRISM, Vector3(0.05, 0.24, 0.05), Vector3(0.0, -0.15, 0.0), GUNMETAL, 0.0,
		{"side": RIGHT, "sides": 6})
	_add(list, &"upper_arm", BOX, Vector3(0.066, 0.17, 0.018), Vector3(0.0, -0.13, -0.034), STEEL, 0.0, metal)
	_add(list, &"upper_arm", BOX, Vector3(0.018, 0.15, 0.056), Vector3(0.036, -0.14, 0.0), RUST, 0.0, {"side": RIGHT})
	_pipe(list, &"upper_arm", Vector3(-0.028, -0.045, 0.03), Vector3(-0.028, -0.14, 0.03), 0.026, GUNMETAL, 6, RIGHT)
	_pipe(list, &"upper_arm", Vector3(-0.028, -0.13, 0.03), Vector3(-0.028, -0.255, 0.03), 0.014, STEEL, 6, RIGHT)
	_pipe(list, &"upper_arm", Vector3(0.012, -0.02, 0.045), Vector3(0.014, -0.25, 0.05), 0.03, HOSE, 6, RIGHT)
	_add(list, &"upper_arm", PRISM, Vector3(0.076, 0.078, 0.076), Vector3(0.0, -0.28, 0.0), GUNMETAL, 0.0,
		_with(metal, {"sides": 8, "rotation_degrees": Vector3(0.0, 0.0, 90.0)}))
	# The arm cannon.
	_add(list, &"forearm", BOX, Vector3(0.086, 0.13, 0.09), Vector3(0.0, -0.07, 0.0), GUNMETAL, 0.0,
		_with(metal, {"chamfer": 0.25}))
	_add(list, &"forearm", PRISM, Vector3(0.118, 0.22, 0.118), Vector3(0.0, -0.25, 0.0), STEEL, 0.0,
		_with(metal, {"sides": 8}))
	for y: float in [-0.18, -0.22]:
		_add(list, &"forearm", PRISM, Vector3(0.14, 0.014, 0.14), Vector3(0.0, y, 0.0), GUNMETAL, 0.0,
			{"side": RIGHT, "sides": 8})
	_add(list, &"forearm", BOX, Vector3(0.02, 0.1, 0.066), Vector3(0.062, -0.3, 0.0), RUST, 0.0, {"side": RIGHT})
	_pipe(list, &"forearm", Vector3(-0.035, -0.05, 0.046), Vector3(-0.052, -0.29, 0.05), 0.02, RUBBER, 6, RIGHT)
	_add(list, &"forearm", PRISM, Vector3(0.1, 0.05, 0.1), Vector3(0.0, -0.375, 0.0), GUNMETAL, 0.0,
		_with(metal, {"sides": 8}))


## Patched olive cargo pants (a cargo pocket on each thigh, a faded patch over the right thigh, a
## knee patch on the left and a strap with a buckle round the right thigh), and laced, scuffed boots
## with the pants bunched over their tops.
static func _legs(list: Array[HumanoidPiece]) -> void:
	_add(list, &"pelvis", BOX, Vector3(0.23, 0.15, 0.17), Vector3(0.0, -0.045, 0.005), PANTS, 0.0,
		{"chamfer": 0.3, "top_scale": Vector2(0.92, 0.9)})
	_add(list, &"thigh", PRISM, Vector3(0.128, 0.34, 0.13), Vector3(0.0, -0.16, 0.0), PANTS, 0.0,
		{"sides": 8, "top_scale": Vector2(1.12, 1.1)})
	_add(list, &"thigh", BOX, Vector3(0.028, 0.095, 0.08), Vector3(0.068, -0.17, 0.0), PANTS_SHADE)
	_add(list, &"thigh", BOX, Vector3(0.032, 0.022, 0.084), Vector3(0.07, -0.118, 0.0), PANTS)
	_add(list, &"thigh", BOX, Vector3(0.07, 0.07, 0.014), Vector3(0.0, -0.3, -0.063), PATCH, 0.0, {"side": LEFT})
	_add(list, &"thigh", BOX, Vector3(0.06, 0.055, 0.012), Vector3(-0.014, -0.1, -0.067), PATCH_GREY, 0.0,
		{"side": RIGHT, "rotation_degrees": Vector3(0.0, 0.0, 8.0)})
	_add(list, &"thigh", BAND, Vector3(0.146, 0.0, 0.146), Vector3(0.0, -0.06, 0.0), STRAP, 0.0, {"side": RIGHT,
		"sides": 8, "profile": PackedVector4Array([Vector4(-0.011, 1.0, 1.0, 0.0), Vector4(0.011, 1.0, 1.0, 0.0)])})
	_add(list, &"thigh", BOX, Vector3(0.03, 0.028, 0.01), Vector3(0.036, -0.06, -0.066), STEEL, 0.0,
		{"side": RIGHT, "shine": METAL_SHINE})
	_add(list, &"shin", PRISM, Vector3(0.118, 0.17, 0.118), Vector3(0.0, -0.08, 0.0), PANTS, 0.0,
		{"sides": 8, "top_scale": Vector2(1.06, 1.06)})
	_add(list, &"shin", PRISM, Vector3(0.124, 0.03, 0.124), Vector3(0.0, -0.165, 0.0), PANTS_SHADE, 0.0, {"sides": 8})
	_add(list, &"shin", PRISM, Vector3(0.098, 0.11, 0.098), Vector3(0.0, -0.215, 0.0), BOOT, 0.0, {"sides": 8})
	# The laces: a crossed pair down the boot's front.
	for z_rot: float in [62.0, -62.0]:
		_add(list, &"shin", BOX, Vector3(0.075, 0.007, 0.005), Vector3(0.0, -0.215, -0.05), LACE, 0.0,
			{"rotation_degrees": Vector3(0.0, 0.0, z_rot)})
	_add(list, &"shin", BOX, Vector3(0.098, 0.07, 0.19), Vector3(0.0, -0.27, -0.04), BOOT, 0.0,
		{"chamfer": 0.3, "top_scale": Vector2(0.9, 0.72), "top_shift": 0.02})
	_add(list, &"shin", BOX, Vector3(0.086, 0.03, 0.035), Vector3(0.0, -0.279, -0.126), BOOT_SCUFF)


## The hosts' purple veins (GDD §9.7): glowing lines along the neck, down the hoodie's sleeve onto
## the back of the hand, and along the cyber arm's hose and piston. Purple on a cyborg always and only
## means "host", so only hosts wear this set.
static func _host_veins() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	var w: float = 0.009
	for vein: Array in [[Vector3(0.034, 0.41, -0.012), Vector3(0.03, 0.47, -0.02)],
			[Vector3(-0.026, 0.405, -0.026), Vector3(-0.03, 0.47, -0.018)],
			[Vector3(0.006, 0.41, -0.036), Vector3(0.012, 0.47, -0.036)]]:
		_vein(list, &"chest", vein[0], vein[1], w, HumanoidPiece.Placement.CENTER)
	for path: Array in [
			[&"upper_arm", Vector3(0.047, -0.03, 0.0), Vector3(0.05, -0.15, 0.012), Vector3(0.045, -0.26, 0.004)],
			[&"upper_arm", Vector3(0.05, -0.15, 0.012), Vector3(0.036, -0.2, 0.034)],
			[&"forearm", Vector3(0.044, -0.01, 0.0), Vector3(0.043, -0.12, 0.014), Vector3(0.036, -0.2, 0.0)],
			[&"forearm", Vector3(0.043, -0.12, 0.014), Vector3(0.024, -0.17, 0.036)],
			[&"forearm", Vector3(0.016, -0.25, 0.012), Vector3(0.016, -0.3, 0.02)]]:
		for k: int in range(1, path.size() - 1):
			_vein(list, path[0], path[k], path[k + 1], w, LEFT)
	_vein(list, &"upper_arm", Vector3(0.012, -0.03, 0.062), Vector3(0.015, -0.25, 0.066), w, RIGHT)
	_vein(list, &"upper_arm", Vector3(-0.028, -0.13, 0.04), Vector3(-0.028, -0.25, 0.04), w, RIGHT)
	_vein(list, &"forearm", Vector3(-0.035, -0.05, 0.058), Vector3(-0.052, -0.28, 0.062), w, RIGHT)
	return list


static func _vein(list: Array[HumanoidPiece], segment: StringName, a: Vector3, b: Vector3, width: float,
		side: HumanoidPiece.Placement) -> void:
	_pipe(list, segment, a, b, width, Kit.GLITCH_COLOR, 4, side, VEIN)


## A cable or hose through `points`: one prism per stretch, overlapping a little at the bends.
static func _cable(list: Array[HumanoidPiece], points: Array[Vector3], width: float, color: Color) -> void:
	for k: int in points.size() - 1:
		_pipe(list, &"chest", points[k], points[k + 1], width, color, 6)


## A `sides`-sided prism from `a` to `b` (a rod, cable or vein), `width` across.
static func _pipe(list: Array[HumanoidPiece], segment: StringName, a: Vector3, b: Vector3, width: float, color: Color,
		sides: int = 6, side: HumanoidPiece.Placement = HumanoidPiece.Placement.CENTER, glow: float = 0.0) -> void:
	var along: Vector3 = b - a
	var y: Vector3 = along.normalized()
	var ref: Vector3 = Vector3.FORWARD if absf(y.dot(Vector3.FORWARD)) < 0.9 else Vector3.RIGHT
	var z: Vector3 = (ref - y * ref.dot(y)).normalized()
	var basis := Basis(y.cross(z), y, z)
	_add(list, segment, PRISM, Vector3(width, along.length() + width * 0.5, width), (a + b) * 0.5, color, glow,
		{"sides": sides, "side": side, "rotation_degrees": basis.get_euler() * (180.0 / PI)})


## A flat bar (a strap) from `a` to `b`, `size` across (width, thickness), its flat side toward `face`.
static func _bar(list: Array[HumanoidPiece], segment: StringName, a: Vector3, b: Vector3, size: Vector2, color: Color,
		face: Vector3) -> void:
	var along: Vector3 = b - a
	var y: Vector3 = along.normalized()
	var z: Vector3 = (face - y * face.dot(y)).normalized()
	var basis := Basis(y.cross(z), y, z)
	_add(list, segment, BOX, Vector3(size.x, along.length() + size.y, size.y), (a + b) * 0.5, color, 0.0,
		{"rotation_degrees": basis.get_euler() * (180.0 / PI)})


## `base` with `more` merged over it (piece options shared by several pieces).
static func _with(base: Dictionary, more: Dictionary) -> Dictionary:
	var out: Dictionary = base.duplicate()
	out.merge(more, true)
	return out


## Adds a piece; `extra` sets any other HumanoidPiece property by name (side, chamfer, profile, ...).
static func _add(list: Array[HumanoidPiece], segment: StringName, shape: HumanoidPiece.Shape, size: Vector3,
		at: Vector3, color: Color, glow: float = 0.0, extra: Dictionary = {}) -> void:
	var piece := HumanoidPiece.new()
	piece.segment = segment
	piece.shape = shape
	piece.size = size
	piece.offset = at
	piece.color = color
	piece.glow = glow
	for key: String in extra:
		piece.set(key, extra[key])
	list.append(piece)
