class_name PlayerSuit
extends RefCounted
## The player's look, generated by code (CLAUDE.md, Assets): Razor Echo (GDD §11, after the owner's
## concept sheet docs/art/reference/player_echo.jpg; brief docs/art/BRIEF_RAZOR_ECHO.md). A weathered
## dark-blue trench coat with a high collar, turned-back lapels and soft glowing copper conduits (along
## the sleeves, round the cuffs and the collar, and a pattern across the back); a gold cybernetic left
## arm with an articulated hand, and a fingerless glove on the right; a copper ocular implant over the
## left eye; a tactical vest, harness straps and a belt; cargo pants with knee pads, worn boots and a
## mechanical brace on the left shin; spiky black hair and a scarred face, no helmet. It is a
## HumanoidParts description for the shared HumanoidRig; the meshes are built once and cached.
##
## Left out on purpose (GDD §11): the sword and scabbard, the holstered pistol (nothing on the base
## model may look like a power-up, so it carries no weapons at all), the coat's graffiti and skull
## emblem, and the vest's cyan lights (cyan is the anti-grav pads'; its lights glow copper).
##
## Colour rule: GLOW, a soft copper, is the player's signature and the only thing on the base model
## that glows. It is kept soft (dim, not very saturated) so bloom never pushes it toward the gap edges'
## bright orange; test_avatar.gd pins it against every hazard colour. The gold arm doesn't glow.
##
## Read from the gameplay camera (behind and above): the copper pattern across the back, the conduits
## down the right sleeve and the gold arm on the left are what the player sees all game; a faint rim
## light (body_material) keeps the dark coat's outline on dark tracks. The coat's skirt is four stiff
## panels hinged at the waist (HumanoidPanel) that the rig swings. The spiky hair and the plain face
## keep the silhouette clearly different from the cyborgs, whose whole head is a screen (GDD §9.2).
##
## Power-up looks (attachment sets, all DESIGN-TBD, OPEN_QUESTIONS §D "How each power-up looks"), each
## in cool steel and white or its own colour, never copper, so they read as added on top:
##   claws        steel blades out of the knuckles of both hands
##   armor        steel plates clipped over the coat's shoulders, chest and upper back (PlayerAvatar
##                shatters them when the armor breaks)
##   weapon_1..4  a gunmetal emitter on a folding mount over the gold arm's shoulder, growing by tier:
##                laser (cyan light), heavier laser (violet), missile pod, heavy four-tube pod (white)
##   magnet       a coil with azure windings on the back of the belt
## The shield is the bubble mesh below (shield_mesh), unchanged.

const CACHE_KEY: String = "player_razor_echo_v1"

## The signature glow: soft copper (conduits, the ocular implant, the vest's lights).
## DESIGN-TBD (docs/questions/p1.md 3): how bright and how deep the copper is.
const GLOW := Color(0.96, 0.64, 0.46)
## The copper thinned toward white, for effects laid over the runner (the dash's shell and lines).
const GLOW_PALE := Color(1.0, 0.8, 0.66)
## Glow amounts (HumanoidPiece.glow): conduits, small lights, the implant's lens. With GLOW_ALBEDO the
## trim shines by its own light at about the bloom threshold: soft, and the same lit or in the dark.
const CONDUIT_GLOW: float = 0.34
const LIGHT_GLOW: float = 0.42
const EYE_GLOW: float = 0.6
const GLOW_ALBEDO: float = 0.35
## Emission of a glow-1 piece (humanoid_body.gdshader's glow_energy).
const GLOW_ENERGY: float = 2.6

const COAT := Color(0.19, 0.22, 0.33)
const COAT_SHADE := Color(0.13, 0.15, 0.24)
const COAT_WORN := Color(0.26, 0.26, 0.29)
const LAPEL := Color(0.25, 0.29, 0.43)
const CUFF := Color(0.17, 0.2, 0.31)
const VEST := Color(0.32, 0.31, 0.27)
const VEST_DARK := Color(0.2, 0.19, 0.17)
const SHIRT := Color(0.09, 0.09, 0.1)
const LEATHER := Color(0.34, 0.24, 0.16)
const BUCKLE := Color(0.58, 0.58, 0.6)
const PANTS := Color(0.22, 0.22, 0.2)
const PANTS_DARK := Color(0.17, 0.17, 0.15)
const PAD := Color(0.11, 0.11, 0.12)
const BOOT := Color(0.25, 0.21, 0.18)
const SOLE := Color(0.08, 0.07, 0.065)
const STEEL := Color(0.5, 0.52, 0.56)
const SKIN := Color(0.8, 0.6, 0.48)
const SCAR := Color(0.66, 0.4, 0.38)
const EYE := Color(0.12, 0.1, 0.1)
const HAIR := Color(0.07, 0.07, 0.08)
const GLOVE := Color(0.15, 0.13, 0.12)
const GOLD := Color(0.88, 0.65, 0.25)
## The gold arm and the implant's brass are polished (HumanoidPiece.shine): they glint, never glow.
const GOLD_SHINE: float = 0.7
const GOLD_DARK := Color(0.46, 0.33, 0.15)
const PLATE := Color(0.33, 0.28, 0.24)

## Power-up colours: steel and white, the shots' own colours, and the magnet's azure.
const GUNMETAL := Color(0.26, 0.28, 0.32)
const ARMOR := Color(0.52, 0.56, 0.62)
const ARMOR_EDGE := Color(0.86, 0.92, 1.0)
const CLAW := Color(0.86, 0.9, 0.96)
const LASER_1 := Color(0.3, 0.9, 1.0)
const LASER_2 := Color(0.75, 0.55, 1.0)
const MISSILE := Color(0.9, 0.95, 1.0)
const MAGNET := Color(0.3, 0.68, 1.0)
const SHIELD := Color(0.35, 0.85, 1.0)

## The rim light that keeps the dark coat's outline on dark tracks (humanoid_body.gdshader).
## DESIGN-TBD (docs/questions/p1.md 4): its colour and strength.
const RIM_COLOR := Color(0.62, 0.7, 0.86)
const RIM_STRENGTH: float = 0.3
const RIM_POWER: float = 3.0

## The gold arm's shoulder weapon: its muzzle in the chest joint's space (the left shoulder, -x).
const WEAPON_MUZZLE := Vector3(-0.2, 0.36, -0.17)

## The skirt: the waist ring the panels hang from (pelvis joint space), its size and flare.
const SKIRT_HINGE_Y: float = 0.03
const SKIRT_HALF := Vector2(0.152, 0.118)
const SKIRT_LENGTH: float = 0.46
const SKIRT_FLARE: float = 1.3

const BOX := HumanoidPiece.Shape.BOX
const PRISM := HumanoidPiece.Shape.PRISM
const LATHE := HumanoidPiece.Shape.LATHE
const BAND := HumanoidPiece.Shape.BAND
const SHELL := HumanoidPiece.Shape.SHELL
const MIRRORED := HumanoidPiece.Placement.MIRRORED
const RIGHT := HumanoidPiece.Placement.RIGHT
const LEFT := HumanoidPiece.Placement.LEFT

const BODY_SHADER: Shader = preload("res://scripts/characters/humanoid_body.gdshader")
const SHIELD_SHADER: Shader = preload("res://scripts/characters/shield_bubble.gdshader")

static var _parts: HumanoidParts
static var _body_material: ShaderMaterial
static var _shield_material: ShaderMaterial
static var _shield_mesh: ArrayMesh


static func parts() -> HumanoidParts:
	if _parts == null:
		_parts = _build_parts()
	return _parts


## The look's shared material. Each avatar uses its own copy (flash, glow and the coat's panels are
## per avatar).
static func body_material() -> ShaderMaterial:
	if _body_material == null:
		_body_material = ShaderMaterial.new()
		_body_material.shader = BODY_SHADER
		_body_material.set_shader_parameter(&"rim_color", RIM_COLOR)
		_body_material.set_shader_parameter(&"rim_strength", RIM_STRENGTH)
		_body_material.set_shader_parameter(&"rim_power", RIM_POWER)
		_body_material.set_shader_parameter(&"glow_albedo", GLOW_ALBEDO)
		_body_material.set_shader_parameter(&"glow_energy", GLOW_ENERGY)
	return _body_material


static func shield_material() -> ShaderMaterial:
	if _shield_material == null:
		_shield_material = ShaderMaterial.new()
		_shield_material.shader = SHIELD_SHADER
		_shield_material.set_shader_parameter(&"color", SHIELD)
	return _shield_material


## DESIGN-TBD: shield look (GDD §8). Placeholder: a translucent bubble round the body, bright at the
## rim; this is its mesh, a low-poly unit sphere faceted like a force field.
static func shield_mesh() -> ArrayMesh:
	if _shield_mesh == null:
		var rings := PackedVector4Array()
		for k: int in 7:
			var a: float = PI * k / 6.0
			rings.append(Vector4(-cos(a), sin(a), sin(a), 0.0))
		var sphere := _piece(&"shield", LATHE, Vector3(2.0, 0.0, 2.0), Vector3.ZERO, SHIELD, 0.0,
			{"sides": 12, "profile": rings})
		var builder := HumanoidMeshBuilder.new()
		builder.add_piece(sphere, false)
		_shield_mesh = ArrayMesh.new()
		_shield_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, builder.arrays())
		_shield_mesh.set_meta(&"triangles", builder.triangle_count())
	return _shield_mesh


static func _build_parts() -> HumanoidParts:
	var p := HumanoidParts.new()
	p.cache_key = CACHE_KEY
	# The runner as modelled, in its run pose: the hair tips average 1.33 m over a stride. Proportional
	# to the grey-box visual_size, so fitting to it scales uniformly.
	p.design_size = Vector3(0.62, 1.33, 0.54)
	var list: Array[HumanoidPiece] = []
	_pelvis(list)
	_torso(list)
	_back(list)
	_head(list)
	_arms(list)
	_gold_arm(list)
	_legs(list)
	p.pieces = list
	p.panels = _skirt()
	p.attachments = {
		&"claws": _claws(),
		&"armor": _armor(),
		&"weapon_1": _weapon(1),
		&"weapon_2": _weapon(2),
		&"weapon_3": _weapon(3),
		&"weapon_4": _weapon(4),
		&"magnet": _magnet(),
	}
	return p


static func _pelvis(list: Array[HumanoidPiece]) -> void:
	# Cargo pants over the hips (seen through the coat's open front).
	_add(list, &"pelvis", BOX, Vector3(0.24, 0.15, 0.17), Vector3(0.0, -0.045, 0.005), PANTS, 0.0,
		{"top_scale": Vector2(1.04, 1.04)})
	# The belt over the coat's waist: it hides where the skirt panels hang from.
	_add(list, &"pelvis", LATHE, Vector3(0.325, 0.0, 0.25), Vector3(0.0, SKIRT_HINGE_Y, 0.005), LEATHER, 0.0,
		{"sides": 8, "profile": PackedVector4Array([Vector4(-0.035, 1.0, 1.0, 0.0), Vector4(0.03, 1.0, 1.0, 0.0)])})
	_add(list, &"pelvis", BOX, Vector3(0.05, 0.04, 0.014), Vector3(0.0, SKIRT_HINGE_Y, -0.127), BUCKLE, 0.0, {"shine": 0.5})


## The coat's body, the tactical vest in its open front, the lapels and the high collar.
static func _torso(list: Array[HumanoidPiece]) -> void:
	_add(list, &"chest", BOX, Vector3(0.28, 0.19, 0.2), Vector3(0.0, 0.02, 0.008), COAT, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(1.07, 1.0)})
	_add(list, &"chest", BOX, Vector3(0.3, 0.15, 0.2), Vector3(0.0, 0.19, 0.008), COAT, 0.0,
		{"chamfer": 0.45, "top_scale": Vector2(0.97, 0.9)})
	# The vest, with a strap across and two copper lights (never cyan: the pads' colour).
	_add(list, &"chest", BOX, Vector3(0.15, 0.25, 0.03), Vector3(0.0, 0.1, -0.097), VEST, 0.0,
		{"top_scale": Vector2(1.06, 1.0)})
	_add(list, &"chest", BOX, Vector3(0.155, 0.024, 0.012), Vector3(0.0, 0.125, -0.117), LEATHER)
	_add(list, &"chest", BOX, Vector3(0.024, 0.013, 0.006), Vector3(0.042, 0.175, -0.115), GLOW, LIGHT_GLOW)
	_add(list, &"chest", BOX, Vector3(0.013, 0.013, 0.006), Vector3(-0.045, 0.085, -0.115), GLOW, LIGHT_GLOW)
	# The dark shirt at the neck, between the lapels.
	_add(list, &"chest", BOX, Vector3(0.085, 0.06, 0.02), Vector3(0.0, 0.245, -0.07), SHIRT)
	# Turned-back lapels, wider at the top.
	_add(list, &"chest", BOX, Vector3(0.055, 0.17, 0.014), Vector3(0.07, 0.19, -0.106), LAPEL, 0.0,
		{"side": MIRRORED, "top_scale": Vector2(1.3, 1.0), "rotation_degrees": Vector3(0.0, 0.0, -12.0)})
	# The high collar, open at the front, and the copper conduit round its back.
	_add(list, &"chest", SHELL, Vector3(0.2, 0.0, 0.18), Vector3(0.0, 0.245, 0.012), COAT_SHADE, 0.0,
		{"sides": 6, "arc": Vector2(-150.0, 150.0), "thickness": 0.014,
			"profile": PackedVector4Array([Vector4(0.0, 1.0, 1.0, 0.0), Vector4(0.1, 1.12, 1.15, 0.012)])})
	_add(list, &"chest", BAND, Vector3(0.214, 0.0, 0.194), Vector3(0.0, 0.245, 0.012), GLOW, CONDUIT_GLOW,
		{"sides": 6, "arc": Vector2(100.0, 260.0),
			"profile": PackedVector4Array([Vector4(0.012, 1.0, 1.0, 0.0), Vector4(0.034, 1.04, 1.05, 0.002)])})


## The copper pattern across the back (the view the player sees all game): a rusted plate carrying
## two conduits (a hook and a cross), joined and dropping into a forked Y down to the belt, framed by
## two long conduits from the shoulders to the belt.
## DESIGN-TBD (docs/questions/p1.md 2): the sheet's pipes, simplified; the owner may want other shapes.
static func _back(list: Array[HumanoidPiece]) -> void:
	_add(list, &"chest", BOX, Vector3(0.16, 0.115, 0.014), Vector3(0.0, 0.19, 0.11), PLATE, 0.0,
		{"rotation_degrees": Vector3(-3.8, 0.0, 0.0)})
	var w: float = 0.024
	var plate := func(x: float, y: float) -> Vector3: return Vector3(x, y, _back_z(y) + 0.02)
	var coat := func(x: float, y: float) -> Vector3: return Vector3(x, y, _back_z(y) + 0.006)
	_pipe(list, &"chest", plate.call(-0.04, 0.138), plate.call(-0.04, 0.228), w)
	_pipe(list, &"chest", plate.call(-0.04, 0.228), plate.call(-0.074, 0.228), w)
	_pipe(list, &"chest", plate.call(0.03, 0.138), plate.call(0.03, 0.238), w)
	_pipe(list, &"chest", plate.call(0.004, 0.205), plate.call(0.062, 0.205), w)
	_pipe(list, &"chest", plate.call(-0.052, 0.138), plate.call(0.042, 0.138), w)
	_pipe(list, &"chest", coat.call(-0.005, 0.14), coat.call(-0.005, 0.095), w)
	_pipe(list, &"chest", coat.call(-0.005, 0.1), coat.call(-0.075, -0.045), w)
	_pipe(list, &"chest", coat.call(-0.005, 0.1), coat.call(0.065, -0.045), w)
	for x: float in [-0.09, 0.09]:
		_pipe(list, &"chest", coat.call(x, 0.255), coat.call(x, -0.055), w)


## The coat's back surface (chest joint space) at height y: the upper torso leans in a little.
static func _back_z(y: float) -> float:
	return 0.108 - 0.067 * clampf(y - 0.115, 0.0, 0.15)


static func _head(list: Array[HumanoidPiece]) -> void:
	_add(list, &"neck", PRISM, Vector3(0.068, 0.08, 0.068), Vector3(0.0, 0.03, 0.0), SKIN)
	# Face and skull.
	_add(list, &"head", LATHE, Vector3(0.15, 0.0, 0.175), Vector3.ZERO, SKIN, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(-0.035, 0.5, 0.55, -0.02), Vector4(0.015, 0.84, 0.86, -0.006),
			Vector4(0.09, 1.0, 1.0, 0.0), Vector4(0.16, 0.8, 0.84, 0.008)])})
	# The hair: a cap from the hairline up, the back of the head down to the nape, short sides, and
	# spikes swept up and back (they break the head's outline from behind).
	var hair_size := Vector3(0.166, 0.0, 0.192)
	var hair_at := Vector3(0.0, 0.0, 0.006)
	_add(list, &"head", LATHE, hair_size, hair_at, HAIR, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(0.128, 0.99, 0.99, 0.004), Vector4(0.162, 0.92, 0.93, 0.008),
			Vector4(0.192, 0.55, 0.58, 0.012)])})
	_add(list, &"head", BAND, hair_size, hair_at, HAIR, 0.0, {"sides": 8, "arc": Vector2(100.0, 260.0),
		"profile": PackedVector4Array([Vector4(0.015, 0.94, 0.93, 0.012), Vector4(0.13, 0.99, 0.99, 0.004)])})
	_add(list, &"head", BAND, hair_size, hair_at, HAIR, 0.0, {"sides": 8, "arc": Vector2(70.0, 110.0), "side": MIRRORED,
		"profile": PackedVector4Array([Vector4(0.065, 0.97, 0.97, 0.006), Vector4(0.13, 0.99, 0.99, 0.004)])})
	for spike: Array in [
			[Vector3(0.0, 0.2, -0.045), Vector3(-35.0, 0.0, 0.0)],
			[Vector3(0.035, 0.195, -0.035), Vector3(-30.0, 0.0, -20.0)],
			[Vector3(0.0, 0.21, 0.01), Vector3(25.0, 0.0, 0.0)],
			[Vector3(-0.035, 0.2, 0.0), Vector3(15.0, 0.0, 25.0)],
			[Vector3(0.0, 0.185, 0.06), Vector3(60.0, 0.0, 0.0)],
			[Vector3(0.035, 0.175, 0.055), Vector3(55.0, 0.0, -25.0)],
			[Vector3(-0.035, 0.175, 0.055), Vector3(55.0, 0.0, 25.0)],
			[Vector3(0.07, 0.15, 0.02), Vector3(30.0, 0.0, -65.0)],
			[Vector3(-0.07, 0.15, 0.02), Vector3(30.0, 0.0, 65.0)],
			# Tufts over the hairline, so it isn't a straight edge.
			[Vector3(-0.04, 0.145, -0.075), Vector3(-75.0, 0.0, 15.0)],
			[Vector3(0.015, 0.15, -0.08), Vector3(-70.0, 0.0, -10.0)],
			[Vector3(0.055, 0.14, -0.065), Vector3(-65.0, 0.0, -35.0)],
			# Swept back over the crown and the nape.
			[Vector3(0.03, 0.12, 0.09), Vector3(105.0, 0.0, -20.0)],
			[Vector3(-0.03, 0.12, 0.09), Vector3(105.0, 0.0, 20.0)],
			[Vector3(0.0, 0.08, 0.1), Vector3(120.0, 0.0, 0.0)]]:
		_add(list, &"head", PRISM, Vector3(0.055, 0.095, 0.055), spike[0], HAIR, 0.0,
			{"sides": 3, "top_scale": Vector2.ZERO, "rotation_degrees": spike[1]})
	# The copper ocular implant over the left eye: a brass housing, the glowing lens, a strut to the
	# temple. (Authored on the right, placed on the left.)
	_add(list, &"head", BOX, Vector3(0.054, 0.04, 0.024), Vector3(0.037, 0.088, -0.074), GOLD, 0.0,
		{"side": LEFT, "shine": GOLD_SHINE})
	_add(list, &"head", BOX, Vector3(0.026, 0.026, 0.012), Vector3(0.037, 0.088, -0.089), GLOW, EYE_GLOW,
		{"side": LEFT})
	_add(list, &"head", BOX, Vector3(0.012, 0.014, 0.06), Vector3(0.068, 0.092, -0.045), GOLD_DARK, 0.0, {"side": LEFT})
	# The right eye and brow, the nose and the scar across the right cheek (on the face's slanted sides).
	_add(list, &"head", BOX, Vector3(0.024, 0.011, 0.006), Vector3(0.036, 0.086, -0.074), EYE, 0.0,
		{"side": RIGHT, "rotation_degrees": Vector3(0.0, -30.0, 0.0)})
	_add(list, &"head", BOX, Vector3(0.046, 0.012, 0.01), Vector3(0.036, 0.104, -0.075), HAIR, 0.0,
		{"side": RIGHT, "rotation_degrees": Vector3(0.0, -30.0, 8.0)})
	_add(list, &"head", BOX, Vector3(0.022, 0.036, 0.022), Vector3(0.0, 0.06, -0.09), SKIN, 0.0,
		{"top_scale": Vector2(0.7, 0.5)})
	_add(list, &"head", BOX, Vector3(0.006, 0.055, 0.004), Vector3(0.053, 0.07, -0.057), SCAR, 0.0,
		{"side": RIGHT, "rotation_degrees": Vector3(0.0, -45.0, 22.0)})


## The right arm in the coat's sleeve: copper conduits along its outside and over the shoulder,
## two copper rings round the turned-back cuff, and the fingerless glove.
static func _arms(list: Array[HumanoidPiece]) -> void:
	_add(list, &"upper_arm", PRISM, Vector3(0.1, 0.22, 0.095), Vector3(0.0, -0.095, 0.0), COAT, 0.0,
		{"side": RIGHT, "top_scale": Vector2(1.15, 1.15)})
	_add(list, &"upper_arm", PRISM, Vector3(0.115, 0.07, 0.125), Vector3(0.012, 0.012, 0.0), COAT, 0.0,
		{"side": RIGHT, "top_scale": Vector2(0.78, 0.82)})
	_pipe(list, &"upper_arm", Vector3(0.058, 0.0, 0.012), Vector3(0.056, -0.19, 0.012), 0.02, Vector3.RIGHT, RIGHT)
	_pipe(list, &"upper_arm", Vector3(0.035, 0.05, -0.05), Vector3(0.035, 0.05, 0.055), 0.02, Vector3.UP, RIGHT)
	_add(list, &"forearm", PRISM, Vector3(0.085, 0.16, 0.08), Vector3(0.0, -0.075, 0.0), COAT, 0.0,
		{"side": RIGHT, "top_scale": Vector2(1.1, 1.1)})
	_add(list, &"forearm", PRISM, Vector3(0.1, 0.045, 0.095), Vector3(0.0, -0.15, 0.0), CUFF, 0.0, {"side": RIGHT})
	for y: float in [-0.137, -0.163]:
		_add(list, &"forearm", BAND, Vector3(0.106, 0.0, 0.101), Vector3(0.0, y, 0.0), GLOW, CONDUIT_GLOW,
			{"side": RIGHT, "sides": 6, "profile": PackedVector4Array([Vector4(-0.005, 1.0, 1.0, 0.0), Vector4(0.005, 1.0, 1.0, 0.0)])})
	_pipe(list, &"forearm", Vector3(0.048, 0.0, 0.01), Vector3(0.046, -0.12, 0.01), 0.018, Vector3.RIGHT, RIGHT)
	_add(list, &"hand", BOX, Vector3(0.06, 0.066, 0.072), Vector3(0.0, -0.035, -0.004), GLOVE, 0.0,
		{"side": RIGHT, "chamfer": 0.35})
	_add(list, &"hand", BOX, Vector3(0.054, 0.032, 0.056), Vector3(0.0, -0.082, -0.01), SKIN, 0.0, {"side": RIGHT})


## The gold cybernetic left arm, from the shoulder down: a domed shoulder with a copper light, the
## upper arm, a dark elbow joint, the forearm with a copper cable, a wrist ring and the articulated
## hand. Dark rings split it into plates; the gold is polished (shine), so it glints as it swings.
## (Authored on the right, placed on the left.)
static func _gold_arm(list: Array[HumanoidPiece]) -> void:
	var gold := {"side": LEFT, "shine": GOLD_SHINE}
	_add(list, &"upper_arm", LATHE, Vector3(0.13, 0.0, 0.13), Vector3(0.012, 0.0, 0.0), GOLD, 0.0, _with(gold, {
		"sides": 6, "profile": PackedVector4Array([Vector4(-0.045, 1.0, 1.0, 0.0), Vector4(0.012, 0.96, 0.96, 0.0),
			Vector4(0.05, 0.55, 0.55, 0.0)])}))
	_add(list, &"upper_arm", BOX, Vector3(0.012, 0.026, 0.026), Vector3(0.078, -0.01, 0.0), GLOW, LIGHT_GLOW,
		{"side": LEFT})
	_add(list, &"upper_arm", PRISM, Vector3(0.076, 0.19, 0.072), Vector3(0.0, -0.1, 0.0), GOLD, 0.0,
		_with(gold, {"top_scale": Vector2(1.1, 1.1)}))
	_add(list, &"upper_arm", BAND, Vector3(0.088, 0.0, 0.084), Vector3(0.0, -0.11, 0.0), GOLD_DARK, 0.0, {"side": LEFT,
		"profile": PackedVector4Array([Vector4(-0.008, 1.0, 1.0, 0.0), Vector4(0.008, 1.0, 1.0, 0.0)])})
	_pipe(list, &"upper_arm", Vector3(0.0, -0.03, 0.04), Vector3(0.0, -0.18, 0.038), 0.014, Vector3.BACK, LEFT, 0.4)
	_add(list, &"upper_arm", PRISM, Vector3(0.07, 0.05, 0.07), Vector3(0.0, -0.2, 0.0), GOLD_DARK, 0.0,
		{"side": LEFT, "shine": 0.4, "rotation_degrees": Vector3(0.0, 0.0, 90.0)})
	_add(list, &"forearm", PRISM, Vector3(0.07, 0.16, 0.066), Vector3(0.0, -0.085, 0.0), GOLD, 0.0,
		_with(gold, {"top_scale": Vector2(1.15, 1.12)}))
	_add(list, &"forearm", BAND, Vector3(0.082, 0.0, 0.078), Vector3(0.0, -0.075, 0.0), GOLD_DARK, 0.0, {"side": LEFT,
		"profile": PackedVector4Array([Vector4(-0.007, 1.0, 1.0, 0.0), Vector4(0.007, 1.0, 1.0, 0.0)])})
	_pipe(list, &"forearm", Vector3(-0.022, -0.02, -0.03), Vector3(-0.02, -0.14, -0.028), 0.012, Vector3.FORWARD, LEFT, 0.4)
	_add(list, &"forearm", PRISM, Vector3(0.07, 0.02, 0.066), Vector3(0.0, -0.165, 0.0), GOLD_DARK, 0.0,
		{"side": LEFT, "shine": 0.4})
	_add(list, &"hand", BOX, Vector3(0.062, 0.066, 0.074), Vector3(0.0, -0.035, -0.004), GOLD, 0.0,
		_with(gold, {"chamfer": 0.35}))
	_add(list, &"hand", BOX, Vector3(0.058, 0.04, 0.058), Vector3(0.0, -0.086, -0.01), GOLD_DARK, 0.0,
		{"side": LEFT, "shine": 0.4})


static func _legs(list: Array[HumanoidPiece]) -> void:
	# Reinforced cargo pants: a pocket on each thigh, a harness strap, knee pads.
	_add(list, &"thigh", PRISM, Vector3(0.115, 0.32, 0.115), Vector3(0.0, -0.145, 0.0), PANTS, 0.0,
		{"top_scale": Vector2(1.2, 1.2)})
	_add(list, &"thigh", BOX, Vector3(0.03, 0.08, 0.062), Vector3(0.062, -0.17, 0.0), PANTS_DARK)
	_add(list, &"thigh", BAND, Vector3(0.144, 0.0, 0.144), Vector3(0.0, -0.075, 0.0), LEATHER, 0.0,
		{"sides": 6, "profile": PackedVector4Array([Vector4(-0.011, 1.0, 1.0, 0.0), Vector4(0.011, 1.0, 1.0, 0.0)])})
	_add(list, &"shin", PRISM, Vector3(0.095, 0.18, 0.095), Vector3(0.0, -0.08, 0.0), PANTS, 0.0,
		{"top_scale": Vector2(1.1, 1.1)})
	_add(list, &"shin", BOX, Vector3(0.08, 0.085, 0.035), Vector3(0.0, -0.012, -0.054), PAD, 0.0,
		{"top_scale": Vector2(0.9, 0.8)})
	# Worn tactical boots.
	_add(list, &"shin", PRISM, Vector3(0.1, 0.15, 0.1), Vector3(0.0, -0.235, 0.0), BOOT, 0.0,
		{"top_scale": Vector2(1.05, 1.05)})
	_add(list, &"foot", BOX, Vector3(0.098, 0.09, 0.2), Vector3(0.0, -0.025, -0.045), BOOT, 0.0,
		{"chamfer": 0.3, "top_scale": Vector2(0.85, 0.7), "top_shift": 0.02})
	_add(list, &"foot", BOX, Vector3(0.102, 0.022, 0.21), Vector3(0.0, -0.064, -0.045), SOLE)
	# The mechanical brace on the left shin: a steel side bar with a copper strip, a hinge disc at the
	# knee and a plate down the front. (Authored on the right, placed on the left.)
	_add(list, &"shin", BOX, Vector3(0.016, 0.26, 0.03), Vector3(0.057, -0.13, 0.0), STEEL, 0.0, {"side": LEFT})
	_pipe(list, &"shin", Vector3(0.067, -0.03, 0.0), Vector3(0.067, -0.23, 0.0), 0.01, Vector3.RIGHT, LEFT, 0.45)
	_add(list, &"shin", PRISM, Vector3(0.042, 0.016, 0.042), Vector3(0.064, 0.0, 0.0), STEEL, 0.0,
		{"side": LEFT, "rotation_degrees": Vector3(0.0, 0.0, 90.0)})
	_add(list, &"shin", BOX, Vector3(0.046, 0.13, 0.012), Vector3(0.0, -0.165, -0.058), STEEL, 0.0, {"side": LEFT})


## The trench coat's skirt, knee to mid-calf: four stiff panels hinged under the belt (two behind the
## legs, split by the back vent, and two at the front edges of the open coat), each following the
## thigh on its side. The back ones carry a copper conduit loop and a weathered hem.
static func _skirt() -> Array[HumanoidPanel]:
	var out: Array[HumanoidPanel] = []
	for side: int in [1, -1]:
		out.append(_skirt_panel(side, true))
		out.append(_skirt_panel(side, false))
	return out


static func _skirt_panel(side: int, behind: bool) -> HumanoidPanel:
	var panel := HumanoidPanel.new()
	panel.side = side
	panel.behind = behind
	panel.length = SKIRT_LENGTH
	# The hinge sits halfway through the panel's depth, so its top edge stays under the belt.
	panel.hinge = Vector3(0.1, SKIRT_HINGE_Y, 0.064) if behind else Vector3(0.13, SKIRT_HINGE_Y, -0.046)
	panel.follow = 0.5 if behind else 0.6
	var pieces: Array[HumanoidPiece] = []
	var at := Vector3(0.0, SKIRT_HINGE_Y, 0.005)
	var arc := Vector2(91.0, 179.0) if behind else Vector2(31.0, 89.0)
	var hem: float = -SKIRT_LENGTH
	# The panel: a flared sheet of the 12-sided waist ring (corners at every 30°).
	pieces.append(_piece(&"pelvis", SHELL, Vector3(SKIRT_HALF.x * 2.0, 0.0, SKIRT_HALF.y * 2.0), at, COAT, 0.0,
		{"sides": 12, "section_phase": 15.0, "arc": arc, "thickness": 0.012,
			"profile": PackedVector4Array([Vector4(0.03, 1.0, 1.0, 0.0), Vector4(hem, SKIRT_FLARE, SKIRT_FLARE, 0.012)])}))
	# A weathered, dusty band along the hem, just outside the sheet.
	var k: float = (SKIRT_LENGTH - 0.07) / SKIRT_LENGTH
	var mid: float = 1.0 + (SKIRT_FLARE - 1.0) * k
	pieces.append(_piece(&"pelvis", BAND, Vector3(SKIRT_HALF.x * 2.0, 0.0, SKIRT_HALF.y * 2.0), at, COAT_WORN, 0.0,
		{"sides": 12, "section_phase": 15.0, "arc": arc, "profile": PackedVector4Array([
			Vector4(hem + 0.002, SKIRT_FLARE + 0.012, SKIRT_FLARE + 0.012, 0.012),
			Vector4(-SKIRT_LENGTH * k, mid + 0.012, mid + 0.012, 0.012 * k)])}))
	if behind:
		# A copper loop down the back of the skirt: down near the vent, across, and back up.
		var p1: Vector3 = _skirt_point(160.0, -0.02)
		var p2: Vector3 = _skirt_point(160.0, -0.3)
		var p3: Vector3 = _skirt_point(118.0, -0.3)
		var p4: Vector3 = _skirt_point(118.0, -0.06)
		for seg: Array in [[p1, p2], [p2, p3], [p3, p4]]:
			var out_dir := Vector3((seg[0] as Vector3).x, 0.0, (seg[0] as Vector3).z - 0.005)
			pieces.append(_pipe_piece(&"pelvis", seg[0], seg[1], 0.022, out_dir.normalized(), GLOW, CONDUIT_GLOW))
	panel.pieces = pieces
	return panel


## A point on the skirt's outside (pelvis joint space) at `angle` degrees round the waist (0 = front,
## 90 = the right side, 180 = back) and `height` below the hinge line.
static func _skirt_point(angle: float, height: float) -> Vector3:
	var t: float = clampf(-height / SKIRT_LENGTH, 0.0, 1.0)
	var scale: float = 1.0 + (SKIRT_FLARE - 1.0) * t
	var a: float = deg_to_rad(angle)
	var r := Vector2(SKIRT_HALF.x * scale + 0.008, SKIRT_HALF.y * scale + 0.008)
	return Vector3(sin(a) * r.x, SKIRT_HINGE_Y + height, -cos(a) * r.y + 0.005 + 0.012 * t)


## DESIGN-TBD: claws look (GDD §8 "Claws / skates"; brief: blades out of the knuckles). Placeholder:
## three steel blades from a knuckle housing on each hand.
static func _claws() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_add(list, &"hand", BOX, Vector3(0.068, 0.022, 0.03), Vector3(0.0, -0.072, -0.03), GUNMETAL)
	for x: float in [-0.021, 0.0, 0.021]:
		_add(list, &"hand", PRISM, Vector3(0.016, 0.16, 0.024), Vector3(x, -0.158, -0.034), CLAW, 0.9,
			{"sides": 3, "top_scale": Vector2(0.12, 0.12), "rotation_degrees": Vector3(180.0, 0.0, 0.0)})
	return list


## DESIGN-TBD: armor look (GDD §8; brief: plates clipped over the coat's shoulders and chest).
## Placeholder: steel plates with a pale edge over both shoulders (they broaden the back-view
## silhouette), a chest plate over the vest and a yoke across the upper back.
static func _armor() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_add(list, &"upper_arm", BOX, Vector3(0.155, 0.05, 0.165), Vector3(0.022, 0.058, 0.0), ARMOR, 0.0,
		{"top_scale": Vector2(0.72, 0.8), "shine": 0.5})
	_add(list, &"upper_arm", BOX, Vector3(0.016, 0.014, 0.15), Vector3(0.1, 0.04, 0.0), ARMOR_EDGE, 0.6)
	_add(list, &"chest", BOX, Vector3(0.17, 0.13, 0.024), Vector3(0.0, 0.15, -0.124), ARMOR, 0.0,
		{"top_scale": Vector2(1.08, 1.0), "shine": 0.5})
	_add(list, &"chest", BOX, Vector3(0.15, 0.012, 0.01), Vector3(0.0, 0.21, -0.137), ARMOR_EDGE, 0.6)
	_add(list, &"chest", BOX, Vector3(0.27, 0.042, 0.024), Vector3(0.0, 0.262, 0.1), ARMOR, 0.0, {"shine": 0.5})
	return list


## DESIGN-TBD: weapon look per tier (GDD §8 weapon line; brief: it unfolds from the gold arm's
## shoulder and grows by tier). Placeholder: a gunmetal emitter on a folding mount over the left
## shoulder, a light on its back showing the tier from behind: a laser (cyan, 1), a heavier laser with
## a cooling fin (violet, 2), a missile pod (3) and a heavy four-tube pod (white, 4).
static func _weapon(tier: int) -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	var glow_color: Color = [LASER_1, LASER_1, LASER_2, MISSILE, MISSILE][tier]
	var body: Vector3 = [Vector3.ZERO, Vector3(0.05, 0.05, 0.15), Vector3(0.062, 0.058, 0.17),
		Vector3(0.09, 0.07, 0.15), Vector3(0.12, 0.09, 0.19)][tier]
	var at := Vector3(0.2, 0.33 + body.y * 0.5, -0.01)
	# The folding mount: a pivot on the shoulder and the arm that lifts the weapon.
	_add(list, &"chest", BOX, Vector3(0.036, 0.028, 0.036), Vector3(0.19, 0.285, 0.02), GUNMETAL, 0.0, {"side": LEFT})
	_add(list, &"chest", BOX, Vector3(0.022, at.y - 0.29, 0.03), Vector3(0.195, (at.y + 0.29) * 0.5, 0.03), GUNMETAL, 0.0,
		{"side": LEFT, "rotation_degrees": Vector3(-12.0, 0.0, 0.0)})
	_add(list, &"chest", BOX, body, at, GUNMETAL, 0.0, {"side": LEFT})
	_add(list, &"chest", BOX, Vector3(body.x * 0.6, body.y * 0.4, 0.008), at + Vector3(0.0, 0.0, body.z * 0.5 + 0.004),
		glow_color, 1.2, {"side": LEFT})
	var front: float = at.z - body.z * 0.5
	if tier <= 2:
		var r: float = 0.03 if tier == 1 else 0.038
		_add(list, &"chest", PRISM, Vector3(r, 0.07, r), Vector3(at.x, at.y, front - 0.035), GUNMETAL, 0.0,
			{"side": LEFT, "rotation_degrees": Vector3(90.0, 0.0, 0.0)})
		_add(list, &"chest", BOX, Vector3(r * 0.75, r * 0.75, 0.01), Vector3(at.x, at.y, front - 0.074), glow_color, 1.6,
			{"side": LEFT})
		if tier == 2:
			_add(list, &"chest", BOX, Vector3(0.008, 0.03, 0.1), at + Vector3(0.0, body.y * 0.5 + 0.015, 0.01), GUNMETAL, 0.0,
				{"side": LEFT})
		return list
	var cols: Array[float] = [at.x - body.x * 0.25, at.x + body.x * 0.25]
	var rows: Array[float] = [at.y]
	if tier >= 4:
		rows = [at.y - body.y * 0.22, at.y + body.y * 0.22]
		_add(list, &"chest", BOX, Vector3(0.012, 0.04, 0.12), at + Vector3(0.0, body.y * 0.5 + 0.02, 0.02), GUNMETAL, 0.0,
			{"side": LEFT})
	for x: float in cols:
		for y: float in rows:
			_add(list, &"chest", BOX, Vector3(0.026, 0.026, 0.01), Vector3(x, y, front - 0.004), glow_color, 1.5,
				{"side": LEFT})
	return list


## DESIGN-TBD: magnet look (GDD §8; brief: a coil on the back of the belt). Placeholder: a gunmetal
## coil across the back of the belt with two glowing azure windings (the magnet's pull glows azure).
static func _magnet() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	var at := Vector3(0.0, SKIRT_HINGE_Y, 0.162)
	var across := Vector3(0.0, 0.0, 90.0)
	_add(list, &"pelvis", PRISM, Vector3(0.058, 0.17, 0.058), at, GUNMETAL, 0.0, {"rotation_degrees": across})
	for x: float in [-0.035, 0.035]:
		_add(list, &"pelvis", BAND, Vector3(0.07, 0.0, 0.07), at + Vector3(x, 0.0, 0.0), MAGNET, 1.1,
			{"sides": 6, "rotation_degrees": across,
				"profile": PackedVector4Array([Vector4(-0.011, 1.0, 1.0, 0.0), Vector4(0.011, 1.0, 1.0, 0.0)])})
	for x: float in [-0.09, 0.09]:
		_add(list, &"pelvis", BOX, Vector3(0.016, 0.076, 0.076), at + Vector3(x, 0.0, 0.0), GUNMETAL)
	return list


## A copper conduit (or cable): a three-sided pipe from `a` to `b` with its flat face toward `face`.
static func _pipe(list: Array[HumanoidPiece], segment: StringName, a: Vector3, b: Vector3, width: float,
		face: Vector3 = Vector3.BACK, side: HumanoidPiece.Placement = HumanoidPiece.Placement.CENTER,
		glow: float = CONDUIT_GLOW) -> void:
	var piece: HumanoidPiece = _pipe_piece(segment, a, b, width, face, GLOW, glow)
	piece.side = side
	list.append(piece)


static func _pipe_piece(segment: StringName, a: Vector3, b: Vector3, width: float, face: Vector3, color: Color,
		glow: float) -> HumanoidPiece:
	var along: Vector3 = b - a
	var y: Vector3 = along.normalized()
	var z: Vector3 = (face - y * face.dot(y)).normalized()
	var basis := Basis(y.cross(z), y, z)
	return _piece(segment, PRISM, Vector3(width, along.length() + width * 0.5, width), (a + b) * 0.5, color, glow,
		{"sides": 3, "rotation_degrees": basis.get_euler() * (180.0 / PI)})


## `base` with `more` merged over it (piece options shared by several pieces).
static func _with(base: Dictionary, more: Dictionary) -> Dictionary:
	var out: Dictionary = base.duplicate()
	out.merge(more, true)
	return out


static func _add(list: Array[HumanoidPiece], segment: StringName, shape: HumanoidPiece.Shape, size: Vector3,
		at: Vector3, color: Color, glow: float = 0.0, extra: Dictionary = {}) -> void:
	list.append(_piece(segment, shape, size, at, color, glow, extra))


## A piece; `extra` sets any other HumanoidPiece property by name (side, chamfer, profile, ...).
static func _piece(segment: StringName, shape: HumanoidPiece.Shape, size: Vector3, at: Vector3, color: Color,
		glow: float = 0.0, extra: Dictionary = {}) -> HumanoidPiece:
	var piece := HumanoidPiece.new()
	piece.segment = segment
	piece.shape = shape
	piece.size = size
	piece.offset = at
	piece.color = color
	piece.glow = glow
	for key: String in extra:
		piece.set(key, extra[key])
	return piece
