class_name PlayerSuit
extends RefCounted
## The player's look, generated by code (CLAUDE.md, Assets): a human runner in a cyber suit
## (GDD §11). A light jacket with a high collar over dark trousers and boots, a rounded helmet with a
## glowing wrap-around visor, and cyan neon trim that blooms. It is a HumanoidParts description for
## the shared HumanoidRig; the meshes are built once and cached.
##
## Read from the gameplay camera (behind and above): the light jacket stands out against the dark
## track; a glowing crest runs over the helmet; a light bar sits on the backpack; glowing seams frame
## the back; glowing stripes on the calves and glowing soles flash as the heels kick up.
## The enemy cyborgs have rectangular LED-screen faces (GDD §9.2). The player's round helmet with a
## continuous visor band is deliberately different.
##
## Equipment attachment sets (all DESIGN-TBD placeholders, OPEN_QUESTIONS §3 "How it looks when
## using each power-up"): claws, armor, weapon_1..weapon_4, magnet. The shield is a bubble mesh.

const CACHE_KEY: String = "player_cyber_suit_v1"

const JACKET := Color(0.86, 0.89, 0.95)
const PANEL := Color(0.5, 0.56, 0.68)
const PANTS := Color(0.33, 0.36, 0.47)
const DARK := Color(0.07, 0.08, 0.11)
const HELMET := Color(0.9, 0.92, 0.97)
const TRIM := Color(0.1, 0.9, 1.0)
const VISOR := Color(0.3, 0.95, 1.0)
const ARMOR := Color(0.42, 0.47, 0.56)
const ARMOR_TRIM := Color(0.6, 0.85, 1.0)
const CLAW := Color(0.8, 0.97, 1.0)
const LASER_1 := Color(0.35, 0.8, 1.0)
const LASER_2 := Color(0.75, 0.45, 1.0)
const MISSILE := Color(1.0, 0.95, 0.85)
const COPPER := Color(0.9, 0.52, 0.25)
const SHIELD := Color(0.35, 0.85, 1.0)

const BOX := HumanoidPiece.Shape.BOX
const PRISM := HumanoidPiece.Shape.PRISM
const LATHE := HumanoidPiece.Shape.LATHE
const BAND := HumanoidPiece.Shape.BAND
const TORUS := HumanoidPiece.Shape.TORUS
const MIRRORED := HumanoidPiece.Placement.MIRRORED
const RIGHT := HumanoidPiece.Placement.RIGHT

const BODY_SHADER: Shader = preload("res://scripts/characters/humanoid_body.gdshader")
const SHIELD_SHADER: Shader = preload("res://scripts/characters/shield_bubble.gdshader")

static var _parts: HumanoidParts
static var _body_material: ShaderMaterial
static var _shield_material: ShaderMaterial
static var _shield_mesh: ArrayMesh


static func parts() -> HumanoidParts:
	if _parts == null:
		_parts = _build_parts()
	return _parts


## The suit's shared material. Each avatar uses its own copy (flash and glow are per avatar).
static func body_material() -> ShaderMaterial:
	if _body_material == null:
		_body_material = ShaderMaterial.new()
		_body_material.shader = BODY_SHADER
	return _body_material


static func shield_material() -> ShaderMaterial:
	if _shield_material == null:
		_shield_material = ShaderMaterial.new()
		_shield_material.shader = SHIELD_SHADER
		_shield_material.set_shader_parameter(&"color", SHIELD)
	return _shield_material


## DESIGN-TBD: shield look (GDD §8). Placeholder: a translucent bubble round the body, bright at the
## rim; this is its mesh, a low-poly unit sphere faceted like a force field.
static func shield_mesh() -> ArrayMesh:
	if _shield_mesh == null:
		var rings := PackedVector4Array()
		for k: int in 7:
			var a: float = PI * k / 6.0
			rings.append(Vector4(-cos(a), sin(a), sin(a), 0.0))
		var sphere := _piece(&"shield", LATHE, Vector3(2.0, 0.0, 2.0), Vector3.ZERO, SHIELD, 0.0,
			{"sides": 12, "profile": rings})
		var builder := HumanoidMeshBuilder.new()
		builder.add_piece(sphere, false)
		_shield_mesh = ArrayMesh.new()
		_shield_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, builder.arrays())
		_shield_mesh.set_meta(&"triangles", builder.triangle_count())
	return _shield_mesh


static func _build_parts() -> HumanoidParts:
	var p := HumanoidParts.new()
	p.cache_key = CACHE_KEY
	# The suit as modelled, in its run pose: the helmet top averages 1.33 m over a stride (standing is
	# 1.36 m). Proportional to the grey-box visual_size, so fitting to it scales uniformly.
	p.design_size = Vector3(0.62, 1.33, 0.54)
	var list: Array[HumanoidPiece] = []
	_pelvis(list)
	_torso(list)
	_head(list)
	_arms(list)
	_legs(list)
	p.pieces = list
	p.attachments = {
		&"claws": _claws(),
		&"armor": _armor(),
		&"weapon_1": _weapon(1),
		&"weapon_2": _weapon(2),
		&"weapon_3": _weapon(3),
		&"weapon_4": _weapon(4),
		&"magnet": _magnet(),
	}
	return p


static func _pelvis(list: Array[HumanoidPiece]) -> void:
	_add(list, &"pelvis", BOX, Vector3(0.25, 0.15, 0.17), Vector3(0.0, -0.045, 0.005), PANTS, 0.0,
		{"chamfer": 0.35, "top_scale": Vector2(1.04, 1.04)})


static func _torso(list: Array[HumanoidPiece]) -> void:
	# The jacket: an octagonal lathe, flared at the hem, broad at the shoulders.
	_add(list, &"chest", LATHE, Vector3(0.27, 0.0, 0.18), Vector3.ZERO, JACKET, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(-0.14, 1.02, 1.04, 0.0), Vector4(-0.06, 0.95, 0.98, 0.0),
			Vector4(0.1, 1.08, 1.06, 0.0), Vector4(0.22, 1.16, 1.02, 0.005), Vector4(0.28, 0.72, 0.8, 0.01)])})
	# Glowing hem line, just outside the jacket.
	_add(list, &"chest", BAND, Vector3(0.27, 0.0, 0.18), Vector3.ZERO, TRIM, 1.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(-0.132, 1.035, 1.058, 0.0), Vector4(-0.112, 1.016, 1.042, 0.0)])})
	# High collar.
	_add(list, &"chest", LATHE, Vector3(0.15, 0.0, 0.14), Vector3.ZERO, PANEL, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(0.25, 1.0, 1.0, 0.015), Vector4(0.34, 1.1, 1.12, 0.02)])})
	# Backpack power cell with a light bar: the main landmark of the back view.
	_add(list, &"chest", BOX, Vector3(0.17, 0.2, 0.06), Vector3(0.0, 0.1, 0.115), DARK, 0.0, {"chamfer": 0.3})
	_add(list, &"chest", BOX, Vector3(0.036, 0.17, 0.012), Vector3(0.0, 0.1, 0.148), TRIM, 1.4)
	# Glowing seams down the back, either side of the pack.
	_add(list, &"chest", BOX, Vector3(0.014, 0.3, 0.014), Vector3(0.093, 0.05, 0.068), TRIM, 1.0,
		{"side": MIRRORED, "rotation_degrees": Vector3(0.0, -35.0, -5.0)})
	# Zip down the front (seen in menus).
	_add(list, &"chest", BOX, Vector3(0.012, 0.3, 0.012), Vector3(0.0, 0.07, -0.098), TRIM, 0.7)
	_add(list, &"neck", PRISM, Vector3(0.09, 0.08, 0.09), Vector3(0.0, 0.03, 0.0), DARK)


static func _head(list: Array[HumanoidPiece]) -> void:
	# Rounded helmet shell.
	_add(list, &"head", LATHE, Vector3(0.236, 0.0, 0.26), Vector3.ZERO, HELMET, 0.0, {"sides": 10,
		"profile": PackedVector4Array([Vector4(-0.035, 0.68, 0.7, 0.01), Vector4(0.0, 0.92, 0.93, 0.01),
			Vector4(0.06, 1.0, 1.0, 0.01), Vector4(0.125, 0.97, 0.97, 0.01), Vector4(0.175, 0.8, 0.8, 0.01),
			Vector4(0.205, 0.45, 0.47, 0.01), Vector4(0.215, 0.0, 0.0, 0.01)])})
	# Dark visor frame and the glowing visor band wrapping round to the ear pods.
	_add(list, &"head", BAND, Vector3(0.236, 0.0, 0.26), Vector3.ZERO, DARK, 0.0, {"sides": 10,
		"arc": Vector2(-104.0, 104.0),
		"profile": PackedVector4Array([Vector4(0.03, 1.02, 1.02, 0.01), Vector4(0.125, 0.99, 0.99, 0.01)])})
	_add(list, &"head", BAND, Vector3(0.236, 0.0, 0.26), Vector3.ZERO, VISOR, 1.3, {"sides": 10,
		"arc": Vector2(-100.0, 100.0),
		"profile": PackedVector4Array([Vector4(0.045, 1.04, 1.04, 0.01), Vector4(0.108, 1.02, 1.02, 0.01)])})
	# Glowing crest from the brow over the top and down the back: the helmet's back-view mark.
	_add(list, &"head", BOX, Vector3(0.024, 0.03, 0.13), Vector3(0.0, 0.212, 0.02), TRIM, 1.3)
	_add(list, &"head", BOX, Vector3(0.024, 0.03, 0.1), Vector3(0.0, 0.172, 0.113), TRIM, 1.3,
		{"rotation_degrees": Vector3(51.0, 0.0, 0.0)})
	_add(list, &"head", BOX, Vector3(0.024, 0.09, 0.024), Vector3(0.0, 0.075, 0.15), TRIM, 1.3)
	# Ear pods where the visor ends.
	_add(list, &"head", PRISM, Vector3(0.07, 0.03, 0.07), Vector3(0.118, 0.07, 0.025), PANEL, 0.0,
		{"side": MIRRORED, "sides": 8, "rotation_degrees": Vector3(0.0, 0.0, 90.0)})
	_add(list, &"head", PRISM, Vector3(0.04, 0.012, 0.04), Vector3(0.136, 0.07, 0.025), TRIM, 1.2,
		{"side": MIRRORED, "sides": 8, "rotation_degrees": Vector3(0.0, 0.0, 90.0)})


static func _arms(list: Array[HumanoidPiece]) -> void:
	_add(list, &"upper_arm", PRISM, Vector3(0.086, 0.22, 0.082), Vector3(0.0, -0.09, 0.0), JACKET, 0.0,
		{"top_scale": Vector2(1.2, 1.2)})
	_add(list, &"upper_arm", BOX, Vector3(0.11, 0.06, 0.12), Vector3(0.012, 0.015, 0.0), PANEL, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(0.8, 0.85)})
	_add(list, &"upper_arm", BOX, Vector3(0.014, 0.014, 0.11), Vector3(0.066, -0.005, 0.0), TRIM, 1.0)
	_add(list, &"upper_arm", BOX, Vector3(0.012, 0.16, 0.012), Vector3(0.045, -0.1, 0.018), TRIM, 0.8)
	_add(list, &"forearm", PRISM, Vector3(0.074, 0.18, 0.07), Vector3(0.0, -0.085, 0.0), JACKET, 0.0,
		{"top_scale": Vector2(1.12, 1.12)})
	_add(list, &"forearm", PRISM, Vector3(0.088, 0.024, 0.084), Vector3(0.0, -0.155, 0.0), TRIM, 1.2)
	_add(list, &"hand", BOX, Vector3(0.066, 0.085, 0.078), Vector3(0.0, -0.045, -0.006), DARK, 0.0, {"chamfer": 0.35})


static func _legs(list: Array[HumanoidPiece]) -> void:
	_add(list, &"thigh", PRISM, Vector3(0.11, 0.33, 0.11), Vector3(0.0, -0.14, 0.0), PANTS, 0.0,
		{"top_scale": Vector2(1.25, 1.25)})
	_add(list, &"thigh", BOX, Vector3(0.012, 0.22, 0.014), Vector3(0.065, -0.13, 0.012), TRIM, 0.7)
	_add(list, &"shin", PRISM, Vector3(0.09, 0.2, 0.09), Vector3(0.0, -0.09, 0.0), PANTS, 0.0,
		{"top_scale": Vector2(1.15, 1.15)})
	_add(list, &"shin", PRISM, Vector3(0.094, 0.14, 0.094), Vector3(0.0, -0.235, 0.0), DARK, 0.0,
		{"top_scale": Vector2(1.1, 1.1)})
	_add(list, &"shin", BOX, Vector3(0.075, 0.075, 0.035), Vector3(0.0, -0.02, -0.05), PANEL, 0.0, {"chamfer": 0.4})
	# Calf stripe: from behind, the two stripes pump up and down with the stride.
	_add(list, &"shin", BOX, Vector3(0.018, 0.2, 0.012), Vector3(0.0, -0.14, 0.052), TRIM, 1.2)
	_add(list, &"foot", BOX, Vector3(0.09, 0.09, 0.2), Vector3(0.0, -0.025, -0.045), DARK, 0.0,
		{"chamfer": 0.3, "top_scale": Vector2(0.85, 0.7), "top_shift": 0.02})
	# Glowing soles and heels: they flash toward the camera as each heel kicks up.
	_add(list, &"foot", BOX, Vector3(0.094, 0.012, 0.205), Vector3(0.0, -0.066, -0.045), TRIM, 0.6)
	_add(list, &"foot", BOX, Vector3(0.05, 0.022, 0.01), Vector3(0.0, -0.04, 0.057), TRIM, 0.9)


## DESIGN-TBD: claws / skates look (GDD §8 "Claws / skates"). Placeholder: three glowing blades on
## each glove.
static func _claws() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	for x: float in [-0.024, 0.0, 0.024]:
		_add(list, &"hand", BOX, Vector3(0.012, 0.15, 0.024), Vector3(x, -0.155, -0.012), CLAW, 1.6,
			{"top_scale": Vector2(0.2, 0.3), "rotation_degrees": Vector3(180.0, 0.0, 0.0)})
	# A glowing knuckle guard that holds the blades.
	_add(list, &"hand", BOX, Vector3(0.074, 0.02, 0.05), Vector3(0.0, -0.085, -0.012), CLAW, 1.0)
	return list


## DESIGN-TBD: armor look (GDD §8). Placeholder: gunmetal plates with pale glowing edges: big shoulder
## plates (they broaden the back-view silhouette), a yoke across the upper back, a chest plate, a
## lower-back plate and shin guards.
static func _armor() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_add(list, &"chest", BOX, Vector3(0.23, 0.15, 0.035), Vector3(0.0, 0.13, -0.1), ARMOR, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(1.08, 1.0)})
	_add(list, &"chest", BOX, Vector3(0.2, 0.014, 0.014), Vector3(0.0, 0.205, -0.118), ARMOR_TRIM, 1.2)
	_add(list, &"chest", BOX, Vector3(0.3, 0.07, 0.05), Vector3(0.0, 0.235, 0.075), ARMOR, 0.0, {"chamfer": 0.4})
	_add(list, &"chest", BOX, Vector3(0.26, 0.014, 0.014), Vector3(0.0, 0.2, 0.1), ARMOR_TRIM, 1.2)
	_add(list, &"chest", BOX, Vector3(0.2, 0.07, 0.035), Vector3(0.0, -0.03, 0.105), ARMOR, 0.0, {"chamfer": 0.4})
	_add(list, &"chest", BOX, Vector3(0.18, 0.014, 0.014), Vector3(0.0, -0.07, 0.122), ARMOR_TRIM, 1.2)
	_add(list, &"upper_arm", BOX, Vector3(0.15, 0.085, 0.16), Vector3(0.022, 0.035, 0.0), ARMOR, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(0.78, 0.85)})
	_add(list, &"upper_arm", BOX, Vector3(0.016, 0.016, 0.15), Vector3(0.096, -0.005, 0.0), ARMOR_TRIM, 1.2)
	_add(list, &"upper_arm", BOX, Vector3(0.12, 0.016, 0.016), Vector3(0.025, -0.005, 0.078), ARMOR_TRIM, 1.2)
	_add(list, &"shin", BOX, Vector3(0.08, 0.16, 0.03), Vector3(0.0, -0.12, -0.05), ARMOR, 0.0, {"chamfer": 0.3})
	return list


## DESIGN-TBD: weapon look per tier (GDD §8 weapon line). Placeholder: an emitter on a post above the
## right shoulder that grows with the tier: a laser (1), a thicker laser in a new colour (2), a missile
## pod (3), a heavy four-tube pod (4). A light on its back shows the tier from behind.
static func _weapon(tier: int) -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	var forward := Vector3(90.0, 0.0, 0.0)
	var glow_color: Color = [LASER_1, LASER_1, LASER_2, MISSILE, MISSILE][tier]
	var body: Vector3 = [Vector3.ZERO, Vector3(0.055, 0.055, 0.16), Vector3(0.07, 0.065, 0.18),
		Vector3(0.1, 0.08, 0.17), Vector3(0.14, 0.1, 0.21)][tier]
	var at := Vector3(0.19 + body.x * 0.2, 0.3 + body.y * 0.5 + 0.02, 0.0)
	_add(list, &"chest", BOX, Vector3(0.04, 0.07, 0.05), Vector3(0.175, 0.29, 0.03), DARK, 0.0, {"side": RIGHT})
	_add(list, &"chest", BOX, body, at, PANEL, 0.0, {"side": RIGHT, "chamfer": 0.3})
	_add(list, &"chest", BOX, Vector3(body.x * 0.7, body.y * 0.45, 0.012), at + Vector3(0.0, 0.0, body.z * 0.5 + 0.004),
		glow_color, 1.4, {"side": RIGHT})
	var front: float = at.z - body.z * 0.5
	if tier <= 2:
		var r: float = 0.035 if tier == 1 else 0.045
		_add(list, &"chest", PRISM, Vector3(r, 0.1, r), Vector3(at.x, at.y, front - 0.04), DARK, 0.0,
			{"side": RIGHT, "rotation_degrees": forward})
		_add(list, &"chest", PRISM, Vector3(r * 0.8, 0.014, r * 0.8), Vector3(at.x, at.y, front - 0.092), glow_color, 1.8,
			{"side": RIGHT, "rotation_degrees": forward})
		return list
	var cols: Array[float] = [at.x - body.x * 0.25, at.x + body.x * 0.25]
	var rows: Array[float] = [at.y]
	if tier >= 4:
		rows = [at.y - body.y * 0.22, at.y + body.y * 0.22]
		_add(list, &"chest", BOX, Vector3(0.014, 0.05, 0.09), at + Vector3(0.0, body.y * 0.5 + 0.02, 0.04), DARK, 0.0,
			{"side": RIGHT})
	for x: float in cols:
		for y: float in rows:
			_add(list, &"chest", PRISM, Vector3(0.028, 0.012, 0.028), Vector3(x, y, front - 0.004), glow_color, 1.6,
				{"side": RIGHT, "rotation_degrees": forward})
	return list


## DESIGN-TBD: magnet look (GDD §8). Placeholder: a copper coil round the backpack's light bar.
static func _magnet() -> Array[HumanoidPiece]:
	var list: Array[HumanoidPiece] = []
	_add(list, &"chest", TORUS, Vector3(0.12, 0.022, 0.0), Vector3(0.0, 0.1, 0.162), COPPER, 0.5,
		{"sides": 12, "rotation_degrees": Vector3(90.0, 0.0, 0.0)})
	return list


static func _add(list: Array[HumanoidPiece], segment: StringName, shape: HumanoidPiece.Shape, size: Vector3,
		at: Vector3, color: Color, glow: float = 0.0, extra: Dictionary = {}) -> void:
	list.append(_piece(segment, shape, size, at, color, glow, extra))


## A piece; `extra` sets any other HumanoidPiece property by name (side, chamfer, profile, ...).
static func _piece(segment: StringName, shape: HumanoidPiece.Shape, size: Vector3, at: Vector3, color: Color,
		glow: float = 0.0, extra: Dictionary = {}) -> HumanoidPiece:
	var piece := HumanoidPiece.new()
	piece.segment = segment
	piece.shape = shape
	piece.size = size
	piece.offset = at
	piece.color = color
	piece.glow = glow
	for key: String in extra:
		piece.set(key, extra[key])
	return piece
