class_name VolleyballRivalSuit
extends RefCounted
## The volleyball match's opponent (the owner, October 10, 2026: "render a new person who is wearing swim trunks"),
## on the shared HumanoidRig like the runner and the cyborgs, generated by code (CLAUDE.md, Assets): a beach
## volleyball player, bare-chested and barefoot, deeply tanned, in long board shorts.
## DESIGN-TBD (docs/questions/volleyball.md): the look. Proposed, in the Beach's palette (GDD §5): ocean-blue board
## shorts with white side stripes, a white waistband and drawstring; sun-bleached hair swept back; dark wraparound
## sunglasses whose thin rim glows violet (the Beach's decorative neon: violet, blue and warm white, never a hazard
## colour) as the world's cyberpunk touch, with the earpiece of a small viewing device (GDD §5, The cult: everyone
## watches the feed; his screen is still small, he isn't one of the cyborgs); a shell necklace and a white wristband.
## Nothing else glows. He is a person, not an enemy: no screen face, no weapon, nothing red or pink, so he never reads
## as a hazard (GDD §5: safe things look safe).
##
## Rig convention (HumanoidPiece): metres at design scale, +y up, -z forward (where he faces), +x his right. Limb
## pieces are authored for the right limb (the left gets a mirrored copy). One material, one draw call per segment.

const CACHE_KEY: String = "volleyball_rival_v1"
## His height as modelled (feet to the top of his hair), standing: VolleyballRival fits it to the tuning's height.
const DESIGN_HEIGHT: float = 1.32

const SKIN := Color(0.66, 0.44, 0.30)
const SKIN_SHADE := Color(0.55, 0.35, 0.23)
const SOLE := Color(0.62, 0.45, 0.34)
const LIPS := Color(0.52, 0.31, 0.24)
const HAIR := Color(0.84, 0.70, 0.43)
const HAIR_ROOT := Color(0.62, 0.47, 0.26)
const BROW := Color(0.45, 0.33, 0.18)
const TRUNKS := Color(0.10, 0.31, 0.58)
const TRUNKS_SHADE := Color(0.07, 0.22, 0.42)
const STRIPE := Color(0.92, 0.93, 0.95)
const SHADES := Color(0.04, 0.045, 0.06)
## The sunglasses' rim: the Beach's decorative violet, soft (HumanoidPiece.glow).
const SHADES_RIM := Color(0.66, 0.46, 1.0)
const SHADES_GLOW: float = 0.7
const SHELL := Color(0.90, 0.86, 0.76)
const CORD := Color(0.30, 0.22, 0.15)
const DEVICE := Color(0.20, 0.21, 0.24)

const RIM_COLOR := Color(0.95, 0.88, 0.74)
const RIM_STRENGTH: float = 0.18
const RIM_POWER: float = 3.0
const GLOW_ALBEDO: float = 0.35
const GLOW_ENERGY: float = 2.6

const BOX := HumanoidPiece.Shape.BOX
const PRISM := HumanoidPiece.Shape.PRISM
const LATHE := HumanoidPiece.Shape.LATHE
const BAND := HumanoidPiece.Shape.BAND
const MIRRORED := HumanoidPiece.Placement.MIRRORED
const RIGHT := HumanoidPiece.Placement.RIGHT
const LEFT := HumanoidPiece.Placement.LEFT

const BODY_SHADER: Shader = preload("res://scripts/characters/humanoid_body.gdshader")

static var _parts: HumanoidParts
static var _material: ShaderMaterial


static func parts() -> HumanoidParts:
	if _parts == null:
		_parts = _build_parts()
	return _parts


## The look's material (one per rival is not needed: nothing on it changes per instance).
static func material() -> ShaderMaterial:
	if _material == null:
		_material = ShaderMaterial.new()
		_material.shader = BODY_SHADER
		_material.set_shader_parameter(&"rim_color", RIM_COLOR)
		_material.set_shader_parameter(&"rim_strength", RIM_STRENGTH)
		_material.set_shader_parameter(&"rim_power", RIM_POWER)
		_material.set_shader_parameter(&"glow_albedo", GLOW_ALBEDO)
		_material.set_shader_parameter(&"glow_energy", GLOW_ENERGY)
	return _material


static func _build_parts() -> HumanoidParts:
	var p := HumanoidParts.new()
	p.cache_key = CACHE_KEY
	p.design_size = Vector3(0.64, DESIGN_HEIGHT, 0.5)
	# An athlete: broader shoulders and a little longer in the arm than the runner's frame.
	p.shoulder_offset = Vector3(0.18, 0.25, 0.0)
	p.upper_arm_length = 0.21
	p.forearm_length = 0.19
	var list: Array[HumanoidPiece] = []
	_trunks(list)
	_torso(list)
	_head(list)
	_arms(list)
	_legs(list)
	p.pieces = list
	return p


## Long board shorts: the seat over the hips, a white waistband with its drawstring, and the legs down to the knee
## (on the thighs), each with a white stripe down its outside and a darker hem.
static func _trunks(list: Array[HumanoidPiece]) -> void:
	_add(list, &"pelvis", BOX, Vector3(0.26, 0.15, 0.19), Vector3(0.0, -0.04, 0.008), TRUNKS, 0.0,
		{"chamfer": 0.3, "top_scale": Vector2(1.03, 1.0)})
	_add(list, &"pelvis", LATHE, Vector3(0.27, 0.0, 0.2), Vector3(0.0, 0.035, 0.008), STRIPE, 0.0,
		{"sides": 8, "profile": PackedVector4Array([Vector4(-0.016, 1.0, 1.0, 0.0), Vector4(0.016, 1.0, 1.0, 0.0)])})
	for x: float in [-0.018, 0.018]:
		_add(list, &"pelvis", BOX, Vector3(0.008, 0.07, 0.006), Vector3(x, -0.005, -0.104), STRIPE, 0.0,
			{"rotation_degrees": Vector3(0.0, 0.0, 8.0 if x > 0.0 else -8.0)})
	_add(list, &"pelvis", BOX, Vector3(0.02, 0.09, 0.006), Vector3(0.12, -0.04, -0.02), STRIPE, 0.0, {"side": MIRRORED})
	_add(list, &"thigh", PRISM, Vector3(0.14, 0.24, 0.14), Vector3(0.0, -0.1, 0.0), TRUNKS, 0.0,
		{"sides": 8, "top_scale": Vector2(1.08, 1.08)})
	_add(list, &"thigh", BOX, Vector3(0.02, 0.24, 0.035), Vector3(0.068, -0.1, 0.0), STRIPE)
	_add(list, &"thigh", LATHE, Vector3(0.148, 0.0, 0.148), Vector3(0.0, -0.215, 0.0), TRUNKS_SHADE, 0.0,
		{"sides": 8, "profile": PackedVector4Array([Vector4(-0.012, 1.0, 1.0, 0.0), Vector4(0.012, 1.0, 1.0, 0.0)])})


## The bare torso: a tapered waist, a broad chest with the pecs and the collarbones shaded in, and the shell
## necklace on its cord.
static func _torso(list: Array[HumanoidPiece]) -> void:
	_add(list, &"chest", BOX, Vector3(0.25, 0.18, 0.17), Vector3(0.0, 0.03, 0.006), SKIN, 0.0,
		{"chamfer": 0.4, "top_scale": Vector2(1.16, 1.06)})
	_add(list, &"chest", BOX, Vector3(0.33, 0.15, 0.19), Vector3(0.0, 0.19, 0.006), SKIN, 0.0,
		{"chamfer": 0.45, "top_scale": Vector2(0.92, 0.88)})
	# The pecs and the line between the abs, a shade darker.
	_add(list, &"chest", BOX, Vector3(0.1, 0.012, 0.01), Vector3(0.055, 0.15, -0.093), SKIN_SHADE, 0.0,
		{"side": MIRRORED, "rotation_degrees": Vector3(0.0, 0.0, 10.0)})
	_add(list, &"chest", BOX, Vector3(0.008, 0.11, 0.008), Vector3(0.0, 0.06, -0.088), SKIN_SHADE)
	# The spine's groove down the back (the camera sees his front; the runner's back, never his).
	_add(list, &"chest", BOX, Vector3(0.008, 0.2, 0.008), Vector3(0.0, 0.12, 0.096), SKIN_SHADE)
	# The shell necklace: a cord round the neck's base with three shells at the front.
	_add(list, &"chest", BAND, Vector3(0.13, 0.0, 0.13), Vector3(0.0, 0.27, 0.0), CORD, 0.0,
		{"sides": 8, "profile": PackedVector4Array([Vector4(-0.006, 1.0, 1.0, 0.0), Vector4(0.006, 1.0, 1.0, 0.0)])})
	for shell: Array in [[Vector3(0.0, 0.245, -0.072), 0.0], [Vector3(0.03, 0.252, -0.066), -25.0],
			[Vector3(-0.03, 0.252, -0.066), 25.0]]:
		_add(list, &"chest", BOX, Vector3(0.022, 0.026, 0.01), shell[0], SHELL, 0.0,
			{"chamfer": 0.4, "rotation_degrees": Vector3(0.0, shell[1], 0.0), "shine": 0.4})


static func _head(list: Array[HumanoidPiece]) -> void:
	_add(list, &"neck", PRISM, Vector3(0.08, 0.08, 0.075), Vector3(0.0, 0.03, 0.0), SKIN)
	# Face and skull: a squarer jaw than the runner's.
	_add(list, &"head", LATHE, Vector3(0.155, 0.0, 0.175), Vector3.ZERO, SKIN, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(-0.035, 0.62, 0.6, -0.018), Vector4(0.012, 0.9, 0.88, -0.006),
			Vector4(0.09, 1.0, 1.0, 0.0), Vector4(0.16, 0.8, 0.84, 0.008)])})
	# Sun-bleached hair: a cap swept back from the hairline, longer at the back, with a few loose tufts.
	var hair_size := Vector3(0.17, 0.0, 0.195)
	var hair_at := Vector3(0.0, 0.0, 0.008)
	_add(list, &"head", LATHE, hair_size, hair_at, HAIR, 0.0, {"sides": 8,
		"profile": PackedVector4Array([Vector4(0.12, 0.99, 0.99, 0.004), Vector4(0.158, 0.93, 0.94, 0.01),
			Vector4(0.188, 0.6, 0.62, 0.016)])})
	_add(list, &"head", BAND, hair_size, hair_at, HAIR_ROOT, 0.0, {"sides": 8, "arc": Vector2(95.0, 265.0),
		"profile": PackedVector4Array([Vector4(0.0, 0.95, 0.94, 0.014), Vector4(0.125, 0.99, 0.99, 0.004)])})
	for tuft: Array in [
			[Vector3(0.0, 0.185, -0.04), Vector3(-60.0, 0.0, 0.0)],
			[Vector3(0.04, 0.178, -0.035), Vector3(-55.0, 0.0, -18.0)],
			[Vector3(-0.04, 0.178, -0.035), Vector3(-55.0, 0.0, 18.0)],
			[Vector3(0.0, 0.19, 0.02), Vector3(70.0, 0.0, 0.0)],
			[Vector3(0.03, 0.16, 0.075), Vector3(115.0, 0.0, -15.0)],
			[Vector3(-0.03, 0.16, 0.075), Vector3(115.0, 0.0, 15.0)]]:
		_add(list, &"head", PRISM, Vector3(0.06, 0.08, 0.05), tuft[0], HAIR, 0.0,
			{"sides": 3, "top_scale": Vector2(0.2, 0.2), "rotation_degrees": tuft[1]})
	# Wraparound sunglasses, their thin rim glowing the Beach's violet, and the device's earpiece on the right.
	_add(list, &"head", BOX, Vector3(0.15, 0.034, 0.024), Vector3(0.0, 0.09, -0.083), SHADES, 0.0, {"shine": 0.8})
	_add(list, &"head", BOX, Vector3(0.154, 0.006, 0.026), Vector3(0.0, 0.108, -0.083), SHADES_RIM, SHADES_GLOW)
	_add(list, &"head", BOX, Vector3(0.012, 0.012, 0.09), Vector3(0.074, 0.098, -0.04), SHADES, 0.0, {"side": MIRRORED})
	_add(list, &"head", BOX, Vector3(0.016, 0.03, 0.022), Vector3(0.082, 0.07, -0.005), DEVICE, 0.0, {"side": RIGHT})
	_add(list, &"head", BOX, Vector3(0.006, 0.01, 0.006), Vector3(0.091, 0.078, -0.012), SHADES_RIM, SHADES_GLOW,
		{"side": RIGHT})
	# Brows over the glasses, the nose, the mouth, the ears.
	_add(list, &"head", BOX, Vector3(0.05, 0.01, 0.01), Vector3(0.036, 0.118, -0.078), BROW, 0.0,
		{"side": MIRRORED, "rotation_degrees": Vector3(0.0, -18.0, -4.0)})
	_add(list, &"head", BOX, Vector3(0.024, 0.04, 0.026), Vector3(0.0, 0.058, -0.092), SKIN, 0.0,
		{"top_scale": Vector2(0.65, 0.45)})
	_add(list, &"head", BOX, Vector3(0.04, 0.008, 0.006), Vector3(0.0, 0.022, -0.082), LIPS)
	_add(list, &"head", BOX, Vector3(0.016, 0.04, 0.028), Vector3(0.08, 0.075, 0.005), SKIN_SHADE, 0.0, {"side": LEFT})


## Bare arms: a rounded shoulder, a strong upper arm and forearm, the hand, and a white wristband on the right.
static func _arms(list: Array[HumanoidPiece]) -> void:
	_add(list, &"upper_arm", LATHE, Vector3(0.12, 0.0, 0.12), Vector3(0.008, 0.0, 0.0), SKIN, 0.0, {
		"sides": 6, "profile": PackedVector4Array([Vector4(-0.05, 1.0, 1.0, 0.0), Vector4(0.01, 0.96, 0.96, 0.0),
			Vector4(0.05, 0.55, 0.55, 0.0)])})
	_add(list, &"upper_arm", PRISM, Vector3(0.09, 0.2, 0.09), Vector3(0.0, -0.105, 0.0), SKIN, 0.0,
		{"top_scale": Vector2(1.15, 1.15)})
	_add(list, &"forearm", PRISM, Vector3(0.072, 0.17, 0.07), Vector3(0.0, -0.085, 0.0), SKIN, 0.0,
		{"top_scale": Vector2(1.18, 1.15)})
	_add(list, &"forearm", BAND, Vector3(0.08, 0.0, 0.078), Vector3(0.0, -0.155, 0.0), STRIPE, 0.0, {"side": RIGHT,
		"sides": 6, "profile": PackedVector4Array([Vector4(-0.014, 1.0, 1.0, 0.0), Vector4(0.014, 1.0, 1.0, 0.0)])})
	_add(list, &"hand", BOX, Vector3(0.058, 0.07, 0.07), Vector3(0.0, -0.04, -0.004), SKIN, 0.0, {"chamfer": 0.35})
	_add(list, &"hand", BOX, Vector3(0.05, 0.035, 0.054), Vector3(0.0, -0.088, -0.01), SKIN_SHADE)


## Bare legs from the shorts' hem down: the knee, the calf and the bare foot with a paler sole.
static func _legs(list: Array[HumanoidPiece]) -> void:
	_add(list, &"thigh", PRISM, Vector3(0.105, 0.1, 0.105), Vector3(0.0, -0.255, 0.0), SKIN)
	_add(list, &"shin", PRISM, Vector3(0.088, 0.27, 0.09), Vector3(0.0, -0.13, 0.006), SKIN, 0.0,
		{"top_scale": Vector2(1.2, 1.25)})
	_add(list, &"foot", BOX, Vector3(0.085, 0.055, 0.18), Vector3(0.0, -0.04, -0.04), SKIN, 0.0,
		{"chamfer": 0.35, "top_scale": Vector2(0.85, 0.7), "top_shift": 0.02})
	_add(list, &"foot", BOX, Vector3(0.088, 0.012, 0.184), Vector3(0.0, -0.066, -0.04), SOLE)


static func _add(list: Array[HumanoidPiece], segment: StringName, shape: HumanoidPiece.Shape, size: Vector3,
		at: Vector3, color: Color, glow: float = 0.0, extra: Dictionary = {}) -> void:
	var piece := HumanoidPiece.new()
	piece.segment = segment
	piece.shape = shape
	piece.size = size
	piece.offset = at
	piece.color = color
	piece.glow = glow
	for key: String in extra:
		piece.set(key, extra[key])
	list.append(piece)
